// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterAcmePluginsDeletePluginRequest struct {
	Id string `json:"id,omitempty"` // Unique identifier for ACME plugin instance.
}

type ClusterAcmePluginsDeletePluginResponse struct{}

// Delete ACME plugin configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/acme/plugins/{id}
func (c *Client) ClusterAcmePluginsDeletePlugin(ctx context.Context, request *ClusterAcmePluginsDeletePluginRequest) (*ClusterAcmePluginsDeletePluginResponse, error) {

	method := "DELETE"
	path := "/cluster/acme/plugins/{id}"

	var response ClusterAcmePluginsDeletePluginResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
