// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuFirewallRefsRefsRequest struct {
	Node string  `query:"node,omitempty"` // The cluster node name.
	Type *string `query:"type,omitempty"` // Only list references of specified type.
	Vmid int64   `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesQemuFirewallRefsRefsResponseItem struct {
	Comment *string `json:"comment,omitempty"` //
	Name    string  `json:"name,omitempty"`    //
	Type    string  `json:"type,omitempty"`    //
}

type NodesQemuFirewallRefsRefsResponse []NodesQemuFirewallRefsRefsResponseItem

// Lists possible IPSet/Alias reference which are allowed in source/dest properties.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/firewall/refs
func (c *Client) NodesQemuFirewallRefsRefs(ctx context.Context, request *NodesQemuFirewallRefsRefsRequest) (*NodesQemuFirewallRefsRefsResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/firewall/refs"

	var response NodesQemuFirewallRefsRefsResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
