// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnZonesIndexRequest struct {
	Pending *bool   `query:"pending,omitempty"` // Display pending config.
	Running *bool   `query:"running,omitempty"` // Display running config.
	Type    *string `query:"type,omitempty"`    // Only list SDN zones of specific type
}

type ClusterSdnZonesIndexResponseItem struct {
	Dns        *string `json:"dns,omitempty"`        //
	Dnszone    *string `json:"dnszone,omitempty"`    //
	Ipam       *string `json:"ipam,omitempty"`       //
	Mtu        *int64  `json:"mtu,omitempty"`        //
	Nodes      *string `json:"nodes,omitempty"`      //
	Pending    *string `json:"pending,omitempty"`    //
	Reversedns *string `json:"reversedns,omitempty"` //
	State      *string `json:"state,omitempty"`      //
	Type       string  `json:"type,omitempty"`       //
	Zone       string  `json:"zone,omitempty"`       //
}

type ClusterSdnZonesIndexResponse []ClusterSdnZonesIndexResponseItem

// SDN zones index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/zones
func (c *Client) ClusterSdnZonesIndex(ctx context.Context, request *ClusterSdnZonesIndexRequest) (*ClusterSdnZonesIndexResponse, error) {

	method := "GET"
	path := "/cluster/sdn/zones"

	var response ClusterSdnZonesIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
