// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnZonesDeleteRequest struct {
	Zone string `json:"zone,omitempty"` // The SDN zone object identifier.
}

type ClusterSdnZonesDeleteResponse struct{}

// Delete sdn zone object configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/zones/{zone}
func (c *Client) ClusterSdnZonesDelete(ctx context.Context, request *ClusterSdnZonesDeleteRequest) (*ClusterSdnZonesDeleteResponse, error) {

	method := "DELETE"
	path := "/cluster/sdn/zones/{zone}"

	var response ClusterSdnZonesDeleteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
