// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessTfaUpdateTfaEntryRequest struct {
	Description *string `json:"description,omitempty"` // A description to distinguish multiple entries from one another
	Enable      *bool   `json:"enable,omitempty"`      // Whether the entry should be enabled for login.
	Id          string  `json:"id,omitempty"`          // A TFA entry id.
	Password    *string `json:"password,omitempty"`    // The current password.
	Userid      string  `json:"userid,omitempty"`      // User ID
}

type AccessTfaUpdateTfaEntryResponse struct{}

// Add a TFA entry for a user.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/tfa/{userid}/{id}
func (c *Client) AccessTfaUpdateTfaEntry(ctx context.Context, request *AccessTfaUpdateTfaEntryRequest) (*AccessTfaUpdateTfaEntryResponse, error) {

	method := "PUT"
	path := "/access/tfa/{userid}/{id}"

	var response AccessTfaUpdateTfaEntryResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
