// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallMacrosGetMacrosRequest interface{}

type ClusterFirewallMacrosGetMacrosResponseItem struct {
	Descr string `json:"descr,omitempty"` // More verbose description (if available).
	Macro string `json:"macro,omitempty"` // Macro name.
}

type ClusterFirewallMacrosGetMacrosResponse []ClusterFirewallMacrosGetMacrosResponseItem

// List available macros
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/macros
func (c *Client) ClusterFirewallMacrosGetMacros(ctx context.Context, request *ClusterFirewallMacrosGetMacrosRequest) (*ClusterFirewallMacrosGetMacrosResponse, error) {

	method := "GET"
	path := "/cluster/firewall/macros"

	var response ClusterFirewallMacrosGetMacrosResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
