// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuVmdiridxRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesQemuVmdiridxResponse []NodesQemuVmdiridxResponseItem

type NodesQemuVmdiridxResponseItem struct {
	Subdir string `json:"subdir,omitempty"` //
}

// Directory index
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}
func (c *Client) NodesQemuVmdiridx(ctx context.Context, request *NodesQemuVmdiridxRequest) (*NodesQemuVmdiridxResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}"

	var response NodesQemuVmdiridxResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
