// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDisksIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesDisksIndexResponseItem struct {
}

type NodesDisksIndexResponse []NodesDisksIndexResponseItem

// Node index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/disks
func (c *Client) NodesDisksIndex(ctx context.Context, request *NodesDisksIndexRequest) (*NodesDisksIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/disks"

	var response NodesDisksIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
