// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesServicesStopServiceStopRequest struct {
	Node    string `json:"node,omitempty"`    // The cluster node name.
	Service string `json:"service,omitempty"` // Service ID
}

type NodesServicesStopServiceStopResponse string

// Stop service.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/services/{service}/stop
func (c *Client) NodesServicesStopServiceStop(ctx context.Context, request *NodesServicesStopServiceStopRequest) (*NodesServicesStopServiceStopResponse, error) {

	method := "POST"
	path := "/nodes/{node}/services/{service}/stop"

	var response NodesServicesStopServiceStopResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
