// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuFirewallRulesDeleteRuleRequest struct {
	Digest *string `json:"digest,omitempty"` // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Node   string  `json:"node,omitempty"`   // The cluster node name.
	Pos    *int64  `json:"pos,omitempty"`    // Update rule at position <pos>.
	Vmid   int64   `json:"vmid,omitempty"`   // The (unique) ID of the VM.
}

type NodesQemuFirewallRulesDeleteRuleResponse struct{}

// Delete rule.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/firewall/rules/{pos}
func (c *Client) NodesQemuFirewallRulesDeleteRule(ctx context.Context, request *NodesQemuFirewallRulesDeleteRuleRequest) (*NodesQemuFirewallRulesDeleteRuleResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/qemu/{vmid}/firewall/rules/{pos}"

	var response NodesQemuFirewallRulesDeleteRuleResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
