// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessOpenidIndexRequest interface{}

type AccessOpenidIndexResponseItem struct {
	Subdir string `json:"subdir,omitempty"` //
}

type AccessOpenidIndexResponse []AccessOpenidIndexResponseItem

// Directory index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/openid
func (c *Client) AccessOpenidIndex(ctx context.Context, request *AccessOpenidIndexRequest) (*AccessOpenidIndexResponse, error) {

	method := "GET"
	path := "/access/openid"

	var response AccessOpenidIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
