// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesSubscriptionSetRequest struct {
	Key  string `json:"key,omitempty"`  // Proxmox VE subscription key
	Node string `json:"node,omitempty"` // The cluster node name.
}

type NodesSubscriptionSetResponse struct{}

// Set subscription key.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/subscription
func (c *Client) NodesSubscriptionSet(ctx context.Context, request *NodesSubscriptionSetRequest) (*NodesSubscriptionSetResponse, error) {

	method := "PUT"
	path := "/nodes/{node}/subscription"

	var response NodesSubscriptionSetResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
