// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCertificatesCustomRemoveCustomCertRequest struct {
	Node    string `json:"node,omitempty"`    // The cluster node name.
	Restart *bool  `json:"restart,omitempty"` // Restart pveproxy.
}

type NodesCertificatesCustomRemoveCustomCertResponse struct{}

// DELETE custom certificate chain and key.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/certificates/custom
func (c *Client) NodesCertificatesCustomRemoveCustomCert(ctx context.Context, request *NodesCertificatesCustomRemoveCustomCertRequest) (*NodesCertificatesCustomRemoveCustomCertResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/certificates/custom"

	var response NodesCertificatesCustomRemoveCustomCertResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
