// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCertificatesAcmeCertificateNewCertificateRequest struct {
	Force *bool  `json:"force,omitempty"` // Overwrite existing custom certificate.
	Node  string `json:"node,omitempty"`  // The cluster node name.
}

type NodesCertificatesAcmeCertificateNewCertificateResponse string

// Order a new certificate from ACME-compatible CA.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/certificates/acme/certificate
func (c *Client) NodesCertificatesAcmeCertificateNewCertificate(ctx context.Context, request *NodesCertificatesAcmeCertificateNewCertificateRequest) (*NodesCertificatesAcmeCertificateNewCertificateResponse, error) {

	method := "POST"
	path := "/nodes/{node}/certificates/acme/certificate"

	var response NodesCertificatesAcmeCertificateNewCertificateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
