// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesAptVersionsVersionsRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesAptVersionsVersionsResponseItem struct {
}

type NodesAptVersionsVersionsResponse []NodesAptVersionsVersionsResponseItem

// Get package information for important Proxmox packages.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/apt/versions
func (c *Client) NodesAptVersionsVersions(ctx context.Context, request *NodesAptVersionsVersionsRequest) (*NodesAptVersionsVersionsResponse, error) {

	method := "GET"
	path := "/nodes/{node}/apt/versions"

	var response NodesAptVersionsVersionsResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
