// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesStorageRrddataRrddataRequest struct {
	Cf        *string `query:"cf,omitempty"`        // The RRD consolidation function
	Node      string  `query:"node,omitempty"`      // The cluster node name.
	Storage   string  `query:"storage,omitempty"`   // The storage identifier.
	Timeframe string  `query:"timeframe,omitempty"` // Specify the time frame you are interested in.
}

type NodesStorageRrddataRrddataResponseItem struct {
}

type NodesStorageRrddataRrddataResponse []NodesStorageRrddataRrddataResponseItem

// Read storage RRD statistics.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/rrddata
func (c *Client) NodesStorageRrddataRrddata(ctx context.Context, request *NodesStorageRrddataRrddataRequest) (*NodesStorageRrddataRrddataResponse, error) {

	method := "GET"
	path := "/nodes/{node}/storage/{storage}/rrddata"

	var response NodesStorageRrddataRrddataResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
