// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallGroupsDeleteSecurityGroupRequest struct {
	Group string `json:"group,omitempty"` // Security Group name.
}

type ClusterFirewallGroupsDeleteSecurityGroupResponse struct{}

// Delete security group.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/groups/{group}
func (c *Client) ClusterFirewallGroupsDeleteSecurityGroup(ctx context.Context, request *ClusterFirewallGroupsDeleteSecurityGroupRequest) (*ClusterFirewallGroupsDeleteSecurityGroupResponse, error) {

	method := "DELETE"
	path := "/cluster/firewall/groups/{group}"

	var response ClusterFirewallGroupsDeleteSecurityGroupResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
