// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterAcmeChallengeSchemaChallengeschemaRequest interface{}

type ClusterAcmeChallengeSchemaChallengeschemaResponseItemSchema interface{}

type ClusterAcmeChallengeSchemaChallengeschemaResponseItem struct {
	Id     string                                                      `json:"id,omitempty"`     //
	Name   string                                                      `json:"name,omitempty"`   // Human readable name, falls back to id
	Schema ClusterAcmeChallengeSchemaChallengeschemaResponseItemSchema `json:"schema,omitempty"` //
	Type   string                                                      `json:"type,omitempty"`   //
}

type ClusterAcmeChallengeSchemaChallengeschemaResponse []ClusterAcmeChallengeSchemaChallengeschemaResponseItem

// Get schema of ACME challenge types.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/acme/challenge-schema
func (c *Client) ClusterAcmeChallengeSchemaChallengeschema(ctx context.Context, request *ClusterAcmeChallengeSchemaChallengeschemaRequest) (*ClusterAcmeChallengeSchemaChallengeschemaResponse, error) {

	method := "GET"
	path := "/cluster/acme/challenge-schema"

	var response ClusterAcmeChallengeSchemaChallengeschemaResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
