// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesStorageContentIndexRequest struct {
	Content *string `query:"content,omitempty"` // Only list content of this type.
	Node    string  `query:"node,omitempty"`    // The cluster node name.
	Storage string  `query:"storage,omitempty"` // The storage identifier.
	Vmid    *int64  `query:"vmid,omitempty"`    // Only list images for this VM
}

// Last backup verification result, only useful for PBS storages.
type NodesStorageContentIndexResponseItemVerification struct {
	State string `json:"state,omitempty"` // Last backup verification state.
	Upid  string `json:"upid,omitempty"`  // Last backup verification UPID.
}

type NodesStorageContentIndexResponseItem struct {
	Ctime        *int64                                            `json:"ctime,omitempty"`        // Creation time (seconds since the UNIX Epoch).
	Encrypted    *string                                           `json:"encrypted,omitempty"`    // If whole backup is encrypted, value is the fingerprint or '1'  if encrypted. Only useful for the Proxmox Backup Server storage type.
	Format       string                                            `json:"format,omitempty"`       // Format identifier ('raw', 'qcow2', 'subvol', 'iso', 'tgz' ...)
	Notes        *string                                           `json:"notes,omitempty"`        // Optional notes. If they contain multiple lines, only the first one is returned here.
	Parent       *string                                           `json:"parent,omitempty"`       // Volume identifier of parent (for linked cloned).
	Protected    *bool                                             `json:"protected,omitempty"`    // Protection status. Currently only supported for backups.
	Size         int64                                             `json:"size,omitempty"`         // Volume size in bytes.
	Used         *int64                                            `json:"used,omitempty"`         // Used space. Please note that most storage plugins do not report anything useful here.
	Verification *NodesStorageContentIndexResponseItemVerification `json:"verification,omitempty"` // Last backup verification result, only useful for PBS storages.
	Vmid         *int64                                            `json:"vmid,omitempty"`         // Associated Owner VMID.
	Volid        string                                            `json:"volid,omitempty"`        // Volume identifier.
}

type NodesStorageContentIndexResponse []NodesStorageContentIndexResponseItem

// List storage content.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/content
func (c *Client) NodesStorageContentIndex(ctx context.Context, request *NodesStorageContentIndexRequest) (*NodesStorageContentIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/storage/{storage}/content"

	var response NodesStorageContentIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
