// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesConfigGetConfigRequest struct {
	Node     string  `query:"node,omitempty"`     // The cluster node name.
	Property *string `query:"property,omitempty"` // Return only a specific property from the node configuration.
}

type NodesConfigGetConfigResponse struct {
	Acme                *string `json:"acme,omitempty"`                  // Node specific ACME settings.
	Acmedomainn         *string `json:"acmedomain[n],omitempty"`         // ACME domain and validation plugin
	Description         *string `json:"description,omitempty"`           // Description for the Node. Shown in the web-interface node notes panel. This is saved as comment inside the configuration file.
	Digest              *string `json:"digest,omitempty"`                // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	StartallOnbootDelay *int64  `json:"startall-onboot-delay,omitempty"` // Initial delay in seconds, before starting all the Virtual Guests with on-boot enabled.
	Wakeonlan           *string `json:"wakeonlan,omitempty"`             // MAC address for wake on LAN
}

// Get node configuration options.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/config
func (c *Client) NodesConfigGetConfig(ctx context.Context, request *NodesConfigGetConfigRequest) (*NodesConfigGetConfigResponse, error) {

	method := "GET"
	path := "/nodes/{node}/config"

	var response NodesConfigGetConfigResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
