// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesNetworkDeleteNetworkRequest struct {
	Iface string `json:"iface,omitempty"` // Network interface name.
	Node  string `json:"node,omitempty"`  // The cluster node name.
}

type NodesNetworkDeleteNetworkResponse struct{}

// Delete network device configuration
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/network/{iface}
func (c *Client) NodesNetworkDeleteNetwork(ctx context.Context, request *NodesNetworkDeleteNetworkRequest) (*NodesNetworkDeleteNetworkResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/network/{iface}"

	var response NodesNetworkDeleteNetworkResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
