// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesRrddataRrddataRequest struct {
	Cf        *string `query:"cf,omitempty"`        // The RRD consolidation function
	Node      string  `query:"node,omitempty"`      // The cluster node name.
	Timeframe string  `query:"timeframe,omitempty"` // Specify the time frame you are interested in.
}

type NodesRrddataRrddataResponse []NodesRrddataRrddataResponseItem

type NodesRrddataRrddataResponseItem struct {
}

// Read node RRD statistics
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/rrddata
func (c *Client) NodesRrddataRrddata(ctx context.Context, request *NodesRrddataRrddataRequest) (*NodesRrddataRrddataResponse, error) {

	method := "GET"
	path := "/nodes/{node}/rrddata"

	var response NodesRrddataRrddataResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
