// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesAptIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesAptIndexResponse []NodesAptIndexResponseItem

type NodesAptIndexResponseItem struct {
	Id string `json:"id,omitempty"` //
}

// Directory index for apt (Advanced Package Tool).
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/apt
func (c *Client) NodesAptIndex(ctx context.Context, request *NodesAptIndexRequest) (*NodesAptIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/apt"

	var response NodesAptIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
