// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephRestartRestartRequest struct {
	Node    string  `json:"node,omitempty"`    // The cluster node name.
	Service *string `json:"service,omitempty"` // Ceph service name.
}

type NodesCephRestartRestartResponse string

// Restart ceph services.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/restart
func (c *Client) NodesCephRestartRestart(ctx context.Context, request *NodesCephRestartRestartRequest) (*NodesCephRestartRestartResponse, error) {

	method := "POST"
	path := "/nodes/{node}/ceph/restart"

	var response NodesCephRestartRestartResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
