// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcSnapshotListRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesLxcSnapshotListResponse []NodesLxcSnapshotListResponseItem

type NodesLxcSnapshotListResponseItem struct {
	Description string  `json:"description,omitempty"` // Snapshot description.
	Name        string  `json:"name,omitempty"`        // Snapshot identifier. Value 'current' identifies the current VM.
	Parent      *string `json:"parent,omitempty"`      // Parent snapshot identifier.
	Snaptime    *int64  `json:"snaptime,omitempty"`    // Snapshot creation time
}

// List all snapshots.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/snapshot
func (c *Client) NodesLxcSnapshotList(ctx context.Context, request *NodesLxcSnapshotListRequest) (*NodesLxcSnapshotListResponse, error) {

	method := "GET"
	path := "/nodes/{node}/lxc/{vmid}/snapshot"

	var response NodesLxcSnapshotListResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
