// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallGroupsDeleteRuleRequest struct {
	Digest *string `json:"digest,omitempty"` // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Group  string  `json:"group,omitempty"`  // Security Group name.
	Pos    *int64  `json:"pos,omitempty"`    // Update rule at position <pos>.
}

type ClusterFirewallGroupsDeleteRuleResponse struct{}

// Delete rule.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/groups/{group}/{pos}
func (c *Client) ClusterFirewallGroupsDeleteRule(ctx context.Context, request *ClusterFirewallGroupsDeleteRuleRequest) (*ClusterFirewallGroupsDeleteRuleResponse, error) {

	method := "DELETE"
	path := "/cluster/firewall/groups/{group}/{pos}"

	var response ClusterFirewallGroupsDeleteRuleResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
