// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephRulesRulesRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesCephRulesRulesResponseItem struct {
}

type NodesCephRulesRulesResponse []NodesCephRulesRulesResponseItem

// List ceph rules.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/rules
func (c *Client) NodesCephRulesRules(ctx context.Context, request *NodesCephRulesRulesRequest) (*NodesCephRulesRulesResponse, error) {

	method := "GET"
	path := "/nodes/{node}/ceph/rules"

	var response NodesCephRulesRulesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
