// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephMonCreatemonRequest struct {
	MonAddress *string `json:"mon-address,omitempty"` // Overwrites autodetected monitor IP address(es). Must be in the public network(s) of Ceph.
	Monid      *string `json:"monid,omitempty"`       // The ID for the monitor, when omitted the same as the nodename
	Node       string  `json:"node,omitempty"`        // The cluster node name.
}

type NodesCephMonCreatemonResponse string

// Create Ceph Monitor and Manager
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/mon/{monid}
func (c *Client) NodesCephMonCreatemon(ctx context.Context, request *NodesCephMonCreatemonRequest) (*NodesCephMonCreatemonResponse, error) {

	method := "POST"
	path := "/nodes/{node}/ceph/mon/{monid}"

	var response NodesCephMonCreatemonResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
