// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterConfigQdeviceStatusRequest interface{}

type ClusterConfigQdeviceStatusResponse interface{}

// Get QDevice status
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/config/qdevice
func (c *Client) ClusterConfigQdeviceStatus(ctx context.Context, request *ClusterConfigQdeviceStatusRequest) (*ClusterConfigQdeviceStatusResponse, error) {

	method := "GET"
	path := "/cluster/config/qdevice"

	var response ClusterConfigQdeviceStatusResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
