// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuResizeResizeVmRequest struct {
	Digest   *string `json:"digest,omitempty"`   // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Disk     string  `json:"disk,omitempty"`     // The disk you want to resize.
	Node     string  `json:"node,omitempty"`     // The cluster node name.
	Size     string  `json:"size,omitempty"`     // The new size. With the `+` sign the value is added to the actual size of the volume and without it, the value is taken as an absolute one. Shrinking disk size is not supported.
	Skiplock *bool   `json:"skiplock,omitempty"` // Ignore locks - only root is allowed to use this option.
	Vmid     int64   `json:"vmid,omitempty"`     // The (unique) ID of the VM.
}

type NodesQemuResizeResizeVmResponse struct{}

// Extend volume size.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/resize
func (c *Client) NodesQemuResizeResizeVm(ctx context.Context, request *NodesQemuResizeResizeVmRequest) (*NodesQemuResizeResizeVmResponse, error) {

	method := "PUT"
	path := "/nodes/{node}/qemu/{vmid}/resize"

	var response NodesQemuResizeResizeVmResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
