// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnDnsDeleteRequest struct {
	Dns string `json:"dns,omitempty"` // The SDN dns object identifier.
}

type ClusterSdnDnsDeleteResponse struct{}

// Delete sdn dns object configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/dns/{dns}
func (c *Client) ClusterSdnDnsDelete(ctx context.Context, request *ClusterSdnDnsDeleteRequest) (*ClusterSdnDnsDeleteResponse, error) {

	method := "DELETE"
	path := "/cluster/sdn/dns/{dns}"

	var response ClusterSdnDnsDeleteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
