// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessGroupsReadGroupRequest struct {
	Groupid string `query:"groupid,omitempty"` //
}

type AccessGroupsReadGroupResponse struct {
	Comment *string                                    `json:"comment,omitempty"` //
	Members []AccessGroupsReadGroupResponseMembersItem `json:"members,omitempty"` //
}

// User ID
type AccessGroupsReadGroupResponseMembersItem string

// Get group configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/groups/{groupid}
func (c *Client) AccessGroupsReadGroup(ctx context.Context, request *AccessGroupsReadGroupRequest) (*AccessGroupsReadGroupResponse, error) {

	method := "GET"
	path := "/access/groups/{groupid}"

	var response AccessGroupsReadGroupResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
