// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesServicesRestartServiceRestartRequest struct {
	Node    string `json:"node,omitempty"`    // The cluster node name.
	Service string `json:"service,omitempty"` // Service ID
}

type NodesServicesRestartServiceRestartResponse string

// Hard restart service. Use reload if you want to reduce interruptions.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/services/{service}/restart
func (c *Client) NodesServicesRestartServiceRestart(ctx context.Context, request *NodesServicesRestartServiceRestartRequest) (*NodesServicesRestartServiceRestartResponse, error) {

	method := "POST"
	path := "/nodes/{node}/services/{service}/restart"

	var response NodesServicesRestartServiceRestartResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
