// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesExecuteExecuteRequest struct {
	Commands string `json:"commands,omitempty"` // JSON encoded array of commands.
	Node     string `json:"node,omitempty"`     // The cluster node name.
}

type NodesExecuteExecuteResponseItem struct {
}

type NodesExecuteExecuteResponse []NodesExecuteExecuteResponseItem

// Execute multiple commands in order.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/execute
func (c *Client) NodesExecuteExecute(ctx context.Context, request *NodesExecuteExecuteRequest) (*NodesExecuteExecuteResponse, error) {

	method := "POST"
	path := "/nodes/{node}/execute"

	var response NodesExecuteExecuteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
