// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnIndexRequest interface{}

type ClusterSdnIndexResponseItem struct {
	Id string `json:"id,omitempty"` //
}

type ClusterSdnIndexResponse []ClusterSdnIndexResponseItem

// Directory index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn
func (c *Client) ClusterSdnIndex(ctx context.Context, request *ClusterSdnIndexRequest) (*ClusterSdnIndexResponse, error) {

	method := "GET"
	path := "/cluster/sdn"

	var response ClusterSdnIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
