// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcPendingVmPendingRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesLxcPendingVmPendingResponseItem struct {
	Delete  *int64  `json:"delete,omitempty"`  // Indicates a pending delete request if present and not 0.
	Key     string  `json:"key,omitempty"`     // Configuration option name.
	Pending *string `json:"pending,omitempty"` // Pending value.
	Value   *string `json:"value,omitempty"`   // Current value.
}

type NodesLxcPendingVmPendingResponse []NodesLxcPendingVmPendingResponseItem

// Get container configuration, including pending changes.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/pending
func (c *Client) NodesLxcPendingVmPending(ctx context.Context, request *NodesLxcPendingVmPendingRequest) (*NodesLxcPendingVmPendingResponse, error) {

	method := "GET"
	path := "/nodes/{node}/lxc/{vmid}/pending"

	var response NodesLxcPendingVmPendingResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
