// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuStatusResetVmResetRequest struct {
	Node     string `json:"node,omitempty"`     // The cluster node name.
	Skiplock *bool  `json:"skiplock,omitempty"` // Ignore locks - only root is allowed to use this option.
	Vmid     int64  `json:"vmid,omitempty"`     // The (unique) ID of the VM.
}

type NodesQemuStatusResetVmResetResponse string

// Reset virtual machine.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/status/reset
func (c *Client) NodesQemuStatusResetVmReset(ctx context.Context, request *NodesQemuStatusResetVmResetRequest) (*NodesQemuStatusResetVmResetResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/status/reset"

	var response NodesQemuStatusResetVmResetResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
