// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesStatusStatusRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesStatusStatusResponse interface{}

// Read node status
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/status
func (c *Client) NodesStatusStatus(ctx context.Context, request *NodesStatusStatusRequest) (*NodesStatusStatusResponse, error) {

	method := "GET"
	path := "/nodes/{node}/status"

	var response NodesStatusStatusResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
