// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesTasksLogReadTaskLogRequest struct {
	Limit *int64 `query:"limit,omitempty"` // The maximum amount of lines that should be printed.
	Node  string `query:"node,omitempty"`  // The cluster node name.
	Start *int64 `query:"start,omitempty"` // The line number to start printing at.
	Upid  string `query:"upid,omitempty"`  // The task's unique ID.
}

type NodesTasksLogReadTaskLogResponseItem struct {
	N int64  `json:"n,omitempty"` // Line number
	T string `json:"t,omitempty"` // Line text
}

type NodesTasksLogReadTaskLogResponse []NodesTasksLogReadTaskLogResponseItem

// Read task log.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/tasks/{upid}/log
func (c *Client) NodesTasksLogReadTaskLog(ctx context.Context, request *NodesTasksLogReadTaskLogRequest) (*NodesTasksLogReadTaskLogResponse, error) {

	method := "GET"
	path := "/nodes/{node}/tasks/{upid}/log"

	var response NodesTasksLogReadTaskLogResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
