// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessUsersIndexRequest struct {
	Enabled *bool `query:"enabled,omitempty"` // Optional filter for enable property.
	Full    *bool `query:"full,omitempty"`    // Include group and token information.
}

type AccessUsersIndexResponseItemTokensItem struct {
	Comment *string `json:"comment,omitempty"` //
	Expire  *int64  `json:"expire,omitempty"`  // API token expiration date (seconds since epoch). '0' means no expiration date.
	Privsep *bool   `json:"privsep,omitempty"` // Restrict API token privileges with separate ACLs (default), or give full privileges of corresponding user.
	Tokenid string  `json:"tokenid,omitempty"` // User-specific token identifier.
}

type AccessUsersIndexResponseItem struct {
	Comment   *string                                   `json:"comment,omitempty"`    //
	Email     *string                                   `json:"email,omitempty"`      //
	Enable    *bool                                     `json:"enable,omitempty"`     // Enable the account (default). You can set this to '0' to disable the account
	Expire    *int64                                    `json:"expire,omitempty"`     // Account expiration date (seconds since epoch). '0' means no expiration date.
	Firstname *string                                   `json:"firstname,omitempty"`  //
	Groups    *string                                   `json:"groups,omitempty"`     //
	Keys      *string                                   `json:"keys,omitempty"`       // Keys for two factor auth (yubico).
	Lastname  *string                                   `json:"lastname,omitempty"`   //
	RealmType *string                                   `json:"realm-type,omitempty"` // The type of the users realm
	Tokens    *[]AccessUsersIndexResponseItemTokensItem `json:"tokens,omitempty"`     //
	Userid    string                                    `json:"userid,omitempty"`     // User ID
}

type AccessUsersIndexResponse []AccessUsersIndexResponseItem

// User index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/users
func (c *Client) AccessUsersIndex(ctx context.Context, request *AccessUsersIndexRequest) (*AccessUsersIndexResponse, error) {

	method := "GET"
	path := "/access/users"

	var response AccessUsersIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
