// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterAcmeAccountDeactivateAccountRequest struct {
	Name *string `json:"name,omitempty"` // ACME account config file name.
}

type ClusterAcmeAccountDeactivateAccountResponse string

// Deactivate existing ACME account at CA.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/acme/account/{name}
func (c *Client) ClusterAcmeAccountDeactivateAccount(ctx context.Context, request *ClusterAcmeAccountDeactivateAccountRequest) (*ClusterAcmeAccountDeactivateAccountResponse, error) {

	method := "DELETE"
	path := "/cluster/acme/account/{name}"

	var response ClusterAcmeAccountDeactivateAccountResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
