// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentFileWriteFileWriteRequest struct {
	Content string `json:"content,omitempty"` // The content to write into the file.
	Encode  *bool  `json:"encode,omitempty"`  // If set, the content will be encoded as base64 (required by QEMU).Otherwise the content needs to be encoded beforehand - defaults to true.
	File    string `json:"file,omitempty"`    // The path to the file.
	Node    string `json:"node,omitempty"`    // The cluster node name.
	Vmid    int64  `json:"vmid,omitempty"`    // The (unique) ID of the VM.
}

type NodesQemuAgentFileWriteFileWriteResponse struct{}

// Writes the given file via guest agent.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/file-write
func (c *Client) NodesQemuAgentFileWriteFileWrite(ctx context.Context, request *NodesQemuAgentFileWriteFileWriteRequest) (*NodesQemuAgentFileWriteFileWriteResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent/file-write"

	var response NodesQemuAgentFileWriteFileWriteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
