// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDisksDirectoryIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesDisksDirectoryIndexResponse []NodesDisksDirectoryIndexResponseItem

type NodesDisksDirectoryIndexResponseItem struct {
	Device   string `json:"device,omitempty"`   // The mounted device.
	Options  string `json:"options,omitempty"`  // The mount options.
	Path     string `json:"path,omitempty"`     // The mount path.
	Type     string `json:"type,omitempty"`     // The filesystem type.
	Unitfile string `json:"unitfile,omitempty"` // The path of the mount unit.
}

// PVE Managed Directory storages.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/disks/directory
func (c *Client) NodesDisksDirectoryIndex(ctx context.Context, request *NodesDisksDirectoryIndexRequest) (*NodesDisksDirectoryIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/disks/directory"

	var response NodesDisksDirectoryIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
