// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallIpsetCreateIpsetRequest struct {
	Comment *string `json:"comment,omitempty"` //
	Digest  *string `json:"digest,omitempty"`  // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Name    string  `json:"name,omitempty"`    // IP set name.
	Rename  *string `json:"rename,omitempty"`  // Rename an existing IPSet. You can set 'rename' to the same value as 'name' to update the 'comment' of an existing IPSet.
}

type ClusterFirewallIpsetCreateIpsetResponse struct{}

// Create new IPSet
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/ipset
func (c *Client) ClusterFirewallIpsetCreateIpset(ctx context.Context, request *ClusterFirewallIpsetCreateIpsetRequest) (*ClusterFirewallIpsetCreateIpsetResponse, error) {

	method := "POST"
	path := "/cluster/firewall/ipset"

	var response ClusterFirewallIpsetCreateIpsetResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
