// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuCloudinitCloudinitUpdateRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Vmid int64  `json:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesQemuCloudinitCloudinitUpdateResponse struct{}

// Regenerate and change cloudinit config drive.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/cloudinit
func (c *Client) NodesQemuCloudinitCloudinitUpdate(ctx context.Context, request *NodesQemuCloudinitCloudinitUpdateRequest) (*NodesQemuCloudinitCloudinitUpdateResponse, error) {

	method := "PUT"
	path := "/nodes/{node}/qemu/{vmid}/cloudinit"

	var response NodesQemuCloudinitCloudinitUpdateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
