// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesConfigSetOptionsRequest struct {
	Acme                *string `json:"acme,omitempty"`                  // Node specific ACME settings.
	Acmedomainn         *string `json:"acmedomain[n],omitempty"`         // ACME domain and validation plugin
	Delete              *string `json:"delete,omitempty"`                // A list of settings you want to delete.
	Description         *string `json:"description,omitempty"`           // Description for the Node. Shown in the web-interface node notes panel. This is saved as comment inside the configuration file.
	Digest              *string `json:"digest,omitempty"`                // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Node                string  `json:"node,omitempty"`                  // The cluster node name.
	StartallOnbootDelay *int64  `json:"startall-onboot-delay,omitempty"` // Initial delay in seconds, before starting all the Virtual Guests with on-boot enabled.
	Wakeonlan           *string `json:"wakeonlan,omitempty"`             // MAC address for wake on LAN
}

type NodesConfigSetOptionsResponse struct{}

// Set node configuration options.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/config
func (c *Client) NodesConfigSetOptions(ctx context.Context, request *NodesConfigSetOptionsRequest) (*NodesConfigSetOptionsResponse, error) {

	method := "PUT"
	path := "/nodes/{node}/config"

	var response NodesConfigSetOptionsResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
