// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterHaStatusManagerStatusManagerStatusRequest interface{}

type ClusterHaStatusManagerStatusManagerStatusResponse interface{}

// Get full HA manger status, including LRM status.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha/status/manager_status
func (c *Client) ClusterHaStatusManagerStatusManagerStatus(ctx context.Context, request *ClusterHaStatusManagerStatusManagerStatusRequest) (*ClusterHaStatusManagerStatusManagerStatusResponse, error) {

	method := "GET"
	path := "/cluster/ha/status/manager_status"

	var response ClusterHaStatusManagerStatusManagerStatusResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
