// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentFsfreezeStatusFsfreezeStatusRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Vmid int64  `json:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentFsfreezeStatusFsfreezeStatusResponse interface{}

// Execute fsfreeze-status.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/fsfreeze-status
func (c *Client) NodesQemuAgentFsfreezeStatusFsfreezeStatus(ctx context.Context, request *NodesQemuAgentFsfreezeStatusFsfreezeStatusRequest) (*NodesQemuAgentFsfreezeStatusFsfreezeStatusResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent/fsfreeze-status"

	var response NodesQemuAgentFsfreezeStatusFsfreezeStatusResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
