// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnVnetsSubnetsDeleteRequest struct {
	Subnet string `json:"subnet,omitempty"` // The SDN subnet object identifier.
	Vnet   string `json:"vnet,omitempty"`   // The SDN vnet object identifier.
}

type ClusterSdnVnetsSubnetsDeleteResponse struct{}

// Delete sdn subnet object configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/vnets/{vnet}/subnets/{subnet}
func (c *Client) ClusterSdnVnetsSubnetsDelete(ctx context.Context, request *ClusterSdnVnetsSubnetsDeleteRequest) (*ClusterSdnVnetsSubnetsDeleteResponse, error) {

	method := "DELETE"
	path := "/cluster/sdn/vnets/{vnet}/subnets/{subnet}"

	var response ClusterSdnVnetsSubnetsDeleteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
