// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesFirewallIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesFirewallIndexResponse []NodesFirewallIndexResponseItem

type NodesFirewallIndexResponseItem struct {
}

// Directory index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/firewall
func (c *Client) NodesFirewallIndex(ctx context.Context, request *NodesFirewallIndexRequest) (*NodesFirewallIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/firewall"

	var response NodesFirewallIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
