// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterJobsScheduleAnalyzeScheduleAnalyzeRequest struct {
	Iterations *int64 `query:"iterations,omitempty"` // Number of event-iteration to simulate and return.
	Schedule   string `query:"schedule,omitempty"`   // Job schedule. The format is a subset of `systemd` calendar events.
	Starttime  *int64 `query:"starttime,omitempty"`  // UNIX timestamp to start the calculation from. Defaults to the current time.
}

// An array of the next <iterations> events since <starttime>.
type ClusterJobsScheduleAnalyzeScheduleAnalyzeResponse []ClusterJobsScheduleAnalyzeScheduleAnalyzeResponseItem

type ClusterJobsScheduleAnalyzeScheduleAnalyzeResponseItem struct {
	Timestamp int64  `json:"timestamp,omitempty"` // UNIX timestamp for the run.
	Utc       string `json:"utc,omitempty"`       // UTC timestamp for the run.
}

// Returns a list of future schedule runtimes.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/jobs/schedule-analyze
func (c *Client) ClusterJobsScheduleAnalyzeScheduleAnalyze(ctx context.Context, request *ClusterJobsScheduleAnalyzeScheduleAnalyzeRequest) (*ClusterJobsScheduleAnalyzeScheduleAnalyzeResponse, error) {

	method := "GET"
	path := "/cluster/jobs/schedule-analyze"

	var response ClusterJobsScheduleAnalyzeScheduleAnalyzeResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
