// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesStorageContentInfoRequest struct {
	Node    string  `query:"node,omitempty"`    // The cluster node name.
	Storage *string `query:"storage,omitempty"` // The storage identifier.
	Volume  string  `query:"volume,omitempty"`  // Volume identifier
}

type NodesStorageContentInfoResponse struct {
	Format    string  `json:"format,omitempty"`    // Format identifier ('raw', 'qcow2', 'subvol', 'iso', 'tgz' ...)
	Notes     *string `json:"notes,omitempty"`     // Optional notes.
	Path      string  `json:"path,omitempty"`      // The Path
	Protected *bool   `json:"protected,omitempty"` // Protection status. Currently only supported for backups.
	Size      int64   `json:"size,omitempty"`      // Volume size in bytes.
	Used      int64   `json:"used,omitempty"`      // Used space. Please note that most storage plugins do not report anything useful here.
}

// Get volume attributes
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/content/{volume}
func (c *Client) NodesStorageContentInfo(ctx context.Context, request *NodesStorageContentInfoRequest) (*NodesStorageContentInfoResponse, error) {

	method := "GET"
	path := "/nodes/{node}/storage/{storage}/content/{volume}"

	var response NodesStorageContentInfoResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
