// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephLogLogRequest struct {
	Limit *int64 `query:"limit,omitempty"` //
	Node  string `query:"node,omitempty"`  // The cluster node name.
	Start *int64 `query:"start,omitempty"` //
}

type NodesCephLogLogResponseItem struct {
	N int64  `json:"n,omitempty"` // Line number
	T string `json:"t,omitempty"` // Line text
}

type NodesCephLogLogResponse []NodesCephLogLogResponseItem

// Read ceph log
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/log
func (c *Client) NodesCephLogLog(ctx context.Context, request *NodesCephLogLogRequest) (*NodesCephLogLogResponse, error) {

	method := "GET"
	path := "/nodes/{node}/ceph/log"

	var response NodesCephLogLogResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
