// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallRulesGetRulesRequest interface{}

type ClusterFirewallRulesGetRulesResponseItem struct {
	Pos int64 `json:"pos,omitempty"` //
}

type ClusterFirewallRulesGetRulesResponse []ClusterFirewallRulesGetRulesResponseItem

// List rules.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/rules
func (c *Client) ClusterFirewallRulesGetRules(ctx context.Context, request *ClusterFirewallRulesGetRulesRequest) (*ClusterFirewallRulesGetRulesResponse, error) {

	method := "GET"
	path := "/cluster/firewall/rules"

	var response ClusterFirewallRulesGetRulesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
