// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuFirewallRulesGetRulesRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesQemuFirewallRulesGetRulesResponse []NodesQemuFirewallRulesGetRulesResponseItem

type NodesQemuFirewallRulesGetRulesResponseItem struct {
	Pos int64 `json:"pos,omitempty"` //
}

// List rules.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/firewall/rules
func (c *Client) NodesQemuFirewallRulesGetRules(ctx context.Context, request *NodesQemuFirewallRulesGetRulesRequest) (*NodesQemuFirewallRulesGetRulesResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/firewall/rules"

	var response NodesQemuFirewallRulesGetRulesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
