// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallAliasesGetAliasesRequest interface{}

type ClusterFirewallAliasesGetAliasesResponse []ClusterFirewallAliasesGetAliasesResponseItem

type ClusterFirewallAliasesGetAliasesResponseItem struct {
	Cidr    string  `json:"cidr,omitempty"`    //
	Comment *string `json:"comment,omitempty"` //
	Digest  string  `json:"digest,omitempty"`  // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Name    string  `json:"name,omitempty"`    //
}

// List aliases
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/aliases
func (c *Client) ClusterFirewallAliasesGetAliases(ctx context.Context, request *ClusterFirewallAliasesGetAliasesRequest) (*ClusterFirewallAliasesGetAliasesResponse, error) {

	method := "GET"
	path := "/cluster/firewall/aliases"

	var response ClusterFirewallAliasesGetAliasesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
