// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterMetricsIndexRequest interface{}

type ClusterMetricsIndexResponseItem struct {
}

type ClusterMetricsIndexResponse []ClusterMetricsIndexResponseItem

// Metrics index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/metrics
func (c *Client) ClusterMetricsIndex(ctx context.Context, request *ClusterMetricsIndexRequest) (*ClusterMetricsIndexResponse, error) {

	method := "GET"
	path := "/cluster/metrics"

	var response ClusterMetricsIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
