// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesScanGlusterfsGlusterfsscanRequest struct {
	Node   string `query:"node,omitempty"`   // The cluster node name.
	Server string `query:"server,omitempty"` // The server address (name or IP).
}

type NodesScanGlusterfsGlusterfsscanResponse []NodesScanGlusterfsGlusterfsscanResponseItem

type NodesScanGlusterfsGlusterfsscanResponseItem struct {
	Volname string `json:"volname,omitempty"` // The volume name.
}

// Scan remote GlusterFS server.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/scan/glusterfs
func (c *Client) NodesScanGlusterfsGlusterfsscan(ctx context.Context, request *NodesScanGlusterfsGlusterfsscanRequest) (*NodesScanGlusterfsGlusterfsscanResponse, error) {

	method := "GET"
	path := "/nodes/{node}/scan/glusterfs"

	var response NodesScanGlusterfsGlusterfsscanResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
