// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterAcmeAccountAccountIndexRequest interface{}

type ClusterAcmeAccountAccountIndexResponseItem struct {
}

type ClusterAcmeAccountAccountIndexResponse []ClusterAcmeAccountAccountIndexResponseItem

// ACMEAccount index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/acme/account
func (c *Client) ClusterAcmeAccountAccountIndex(ctx context.Context, request *ClusterAcmeAccountAccountIndexRequest) (*ClusterAcmeAccountAccountIndexResponse, error) {

	method := "GET"
	path := "/cluster/acme/account"

	var response ClusterAcmeAccountAccountIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
