// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDisksLvmthinIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesDisksLvmthinIndexResponseItem struct {
	Lv           string `json:"lv,omitempty"`            // The name of the thinpool.
	LvSize       int64  `json:"lv_size,omitempty"`       // The size of the thinpool in bytes.
	MetadataSize int64  `json:"metadata_size,omitempty"` // The size of the metadata lv in bytes.
	MetadataUsed int64  `json:"metadata_used,omitempty"` // The used bytes of the metadata lv.
	Used         int64  `json:"used,omitempty"`          // The used bytes of the thinpool.
	Vg           string `json:"vg,omitempty"`            // The associated volume group.
}

type NodesDisksLvmthinIndexResponse []NodesDisksLvmthinIndexResponseItem

// List LVM thinpools
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/disks/lvmthin
func (c *Client) NodesDisksLvmthinIndex(ctx context.Context, request *NodesDisksLvmthinIndexRequest) (*NodesDisksLvmthinIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/disks/lvmthin"

	var response NodesDisksLvmthinIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
