// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterBackupInfoIndexRequest interface{}

// Directory index.
type ClusterBackupInfoIndexResponse []ClusterBackupInfoIndexResponseItem

type ClusterBackupInfoIndexResponseItem struct {
	Subdir string `json:"subdir,omitempty"` // API sub-directory endpoint
}

// Index for backup info related endpoints
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/backup-info
func (c *Client) ClusterBackupInfoIndex(ctx context.Context, request *ClusterBackupInfoIndexRequest) (*ClusterBackupInfoIndexResponse, error) {

	method := "GET"
	path := "/cluster/backup-info"

	var response ClusterBackupInfoIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
