// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesReplicationScheduleNowScheduleNowRequest struct {
	Id   string `json:"id,omitempty"`   // Replication Job ID. The ID is composed of a Guest ID and a job number, separated by a hyphen, i.e. '<GUEST>-<JOBNUM>'.
	Node string `json:"node,omitempty"` // The cluster node name.
}

type NodesReplicationScheduleNowScheduleNowResponse string

// Schedule replication job to start as soon as possible.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/replication/{id}/schedule_now
func (c *Client) NodesReplicationScheduleNowScheduleNow(ctx context.Context, request *NodesReplicationScheduleNowScheduleNowRequest) (*NodesReplicationScheduleNowScheduleNowResponse, error) {

	method := "POST"
	path := "/nodes/{node}/replication/{id}/schedule_now"

	var response NodesReplicationScheduleNowScheduleNowResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
