// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesStorageStatusReadStatusRequest struct {
	Node    string `query:"node,omitempty"`    // The cluster node name.
	Storage string `query:"storage,omitempty"` // The storage identifier.
}

type NodesStorageStatusReadStatusResponse interface{}

// Read storage status.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/status
func (c *Client) NodesStorageStatusReadStatus(ctx context.Context, request *NodesStorageStatusReadStatusRequest) (*NodesStorageStatusReadStatusResponse, error) {

	method := "GET"
	path := "/nodes/{node}/storage/{storage}/status"

	var response NodesStorageStatusReadStatusResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
