// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDisksZfsIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesDisksZfsIndexResponse []NodesDisksZfsIndexResponseItem

type NodesDisksZfsIndexResponseItem struct {
	Alloc  int64   `json:"alloc,omitempty"`  //
	Dedup  float64 `json:"dedup,omitempty"`  //
	Frag   int64   `json:"frag,omitempty"`   //
	Free   int64   `json:"free,omitempty"`   //
	Health string  `json:"health,omitempty"` //
	Name   string  `json:"name,omitempty"`   //
	Size   int64   `json:"size,omitempty"`   //
}

// List Zpools.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/disks/zfs
func (c *Client) NodesDisksZfsIndex(ctx context.Context, request *NodesDisksZfsIndexRequest) (*NodesDisksZfsIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/disks/zfs"

	var response NodesDisksZfsIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
