// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessOpenidLoginLoginRequest struct {
	Code        string `json:"code,omitempty"`         // OpenId authorization code.
	RedirectUrl string `json:"redirect-url,omitempty"` // Redirection Url. The client should set this to the used server url (location.origin).
	State       string `json:"state,omitempty"`        // OpenId state.
}

type AccessOpenidLoginLoginResponseCap interface{}

type AccessOpenidLoginLoginResponse struct {
	CSRFPreventionToken string                            `json:"CSRFPreventionToken,omitempty"` //
	Cap                 AccessOpenidLoginLoginResponseCap `json:"cap,omitempty"`                 //
	Clustername         *string                           `json:"clustername,omitempty"`         //
	Ticket              string                            `json:"ticket,omitempty"`              //
	Username            string                            `json:"username,omitempty"`            //
}

//	Verify OpenID authorization code and create a ticket.
//
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/openid/login
func (c *Client) AccessOpenidLoginLogin(ctx context.Context, request *AccessOpenidLoginLoginRequest) (*AccessOpenidLoginLoginResponse, error) {

	method := "POST"
	path := "/access/openid/login"

	var response AccessOpenidLoginLoginResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
