// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuSnapshotSnapshotRequest struct {
	Description *string `json:"description,omitempty"` // A textual description or comment.
	Node        string  `json:"node,omitempty"`        // The cluster node name.
	Snapname    string  `json:"snapname,omitempty"`    // The name of the snapshot.
	Vmid        int64   `json:"vmid,omitempty"`        // The (unique) ID of the VM.
	Vmstate     *bool   `json:"vmstate,omitempty"`     // Save the vmstate
}

// the task ID.
type NodesQemuSnapshotSnapshotResponse string

// Snapshot a VM.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/snapshot
func (c *Client) NodesQemuSnapshotSnapshot(ctx context.Context, request *NodesQemuSnapshotSnapshotRequest) (*NodesQemuSnapshotSnapshotResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/snapshot"

	var response NodesQemuSnapshotSnapshotResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
