// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessRolesUpdateRoleRequest struct {
	Append *bool   `json:"append,omitempty"` //
	Privs  *string `json:"privs,omitempty"`  //
	Roleid string  `json:"roleid,omitempty"` //
}

type AccessRolesUpdateRoleResponse struct{}

// Update an existing role.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/roles/{roleid}
func (c *Client) AccessRolesUpdateRole(ctx context.Context, request *AccessRolesUpdateRoleRequest) (*AccessRolesUpdateRoleResponse, error) {

	method := "PUT"
	path := "/access/roles/{roleid}"

	var response AccessRolesUpdateRoleResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
