// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesAptUpdateUpdateDatabaseRequest struct {
	Node   string `json:"node,omitempty"`   // The cluster node name.
	Notify *bool  `json:"notify,omitempty"` // Send notification mail about new packages (to email address specified for user 'root@pam').
	Quiet  *bool  `json:"quiet,omitempty"`  // Only produces output suitable for logging, omitting progress indicators.
}

type NodesAptUpdateUpdateDatabaseResponse string

// This is used to resynchronize the package index files from their sources (apt-get update).
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/apt/update
func (c *Client) NodesAptUpdateUpdateDatabase(ctx context.Context, request *NodesAptUpdateUpdateDatabaseRequest) (*NodesAptUpdateUpdateDatabaseResponse, error) {

	method := "POST"
	path := "/nodes/{node}/apt/update"

	var response NodesAptUpdateUpdateDatabaseResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
