// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type StorageIndexRequest struct {
	Type *string `query:"type,omitempty"` // Only list storage of specific type
}

type StorageIndexResponse []StorageIndexResponseItem

type StorageIndexResponseItem struct {
	Storage string `json:"storage,omitempty"` //
}

// Storage index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/storage
func (c *Client) StorageIndex(ctx context.Context, request *StorageIndexRequest) (*StorageIndexResponse, error) {

	method := "GET"
	path := "/storage"

	var response StorageIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
