// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephMgrDestroymgrRequest struct {
	Id   string `json:"id,omitempty"`   // The ID of the manager
	Node string `json:"node,omitempty"` // The cluster node name.
}

type NodesCephMgrDestroymgrResponse string

// Destroy Ceph Manager.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/mgr/{id}
func (c *Client) NodesCephMgrDestroymgr(ctx context.Context, request *NodesCephMgrDestroymgrRequest) (*NodesCephMgrDestroymgrResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/ceph/mgr/{id}"

	var response NodesCephMgrDestroymgrResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
