// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessUsersTokenReadTokenRequest struct {
	Tokenid string `query:"tokenid,omitempty"` // User-specific token identifier.
	Userid  string `query:"userid,omitempty"`  // User ID
}

type AccessUsersTokenReadTokenResponse struct {
	Comment *string `json:"comment,omitempty"` //
	Expire  *int64  `json:"expire,omitempty"`  // API token expiration date (seconds since epoch). '0' means no expiration date.
	Privsep *bool   `json:"privsep,omitempty"` // Restrict API token privileges with separate ACLs (default), or give full privileges of corresponding user.
}

// Get specific API token information.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/users/{userid}/token/{tokenid}
func (c *Client) AccessUsersTokenReadToken(ctx context.Context, request *AccessUsersTokenReadTokenRequest) (*AccessUsersTokenReadTokenResponse, error) {

	method := "GET"
	path := "/access/users/{userid}/token/{tokenid}"

	var response AccessUsersTokenReadTokenResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
