// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterAcmePluginsGetPluginConfigRequest struct {
	Id string `query:"id,omitempty"` // Unique identifier for ACME plugin instance.
}

type ClusterAcmePluginsGetPluginConfigResponse interface{}

// Get ACME plugin configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/acme/plugins/{id}
func (c *Client) ClusterAcmePluginsGetPluginConfig(ctx context.Context, request *ClusterAcmePluginsGetPluginConfigRequest) (*ClusterAcmePluginsGetPluginConfigResponse, error) {

	method := "GET"
	path := "/cluster/acme/plugins/{id}"

	var response ClusterAcmePluginsGetPluginConfigResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
