// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesFirewallRulesDeleteRuleRequest struct {
	Digest *string `json:"digest,omitempty"` // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Node   string  `json:"node,omitempty"`   // The cluster node name.
	Pos    *int64  `json:"pos,omitempty"`    // Update rule at position <pos>.
}

type NodesFirewallRulesDeleteRuleResponse struct{}

// Delete rule.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/firewall/rules/{pos}
func (c *Client) NodesFirewallRulesDeleteRule(ctx context.Context, request *NodesFirewallRulesDeleteRuleRequest) (*NodesFirewallRulesDeleteRuleResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/firewall/rules/{pos}"

	var response NodesFirewallRulesDeleteRuleResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
