// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesJournalJournalRequest struct {
	Endcursor   *string `query:"endcursor,omitempty"`   // End before the given Cursor. Conflicts with 'until'
	Lastentries *int64  `query:"lastentries,omitempty"` // Limit to the last X lines. Conflicts with a range.
	Node        string  `query:"node,omitempty"`        // The cluster node name.
	Since       *int64  `query:"since,omitempty"`       // Display all log since this UNIX epoch. Conflicts with 'startcursor'.
	Startcursor *string `query:"startcursor,omitempty"` // Start after the given Cursor. Conflicts with 'since'
	Until       *int64  `query:"until,omitempty"`       // Display all log until this UNIX epoch. Conflicts with 'endcursor'.
}

type NodesJournalJournalResponse []string

// Read Journal
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/journal
func (c *Client) NodesJournalJournal(ctx context.Context, request *NodesJournalJournalRequest) (*NodesJournalJournalResponse, error) {

	method := "GET"
	path := "/nodes/{node}/journal"

	var response NodesJournalJournalResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
