// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcSnapshotConfigGetSnapshotConfigRequest struct {
	Node     string `query:"node,omitempty"`     // The cluster node name.
	Snapname string `query:"snapname,omitempty"` // The name of the snapshot.
	Vmid     int64  `query:"vmid,omitempty"`     // The (unique) ID of the VM.
}

type NodesLxcSnapshotConfigGetSnapshotConfigResponse interface{}

// Get snapshot configuration
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/snapshot/{snapname}/config
func (c *Client) NodesLxcSnapshotConfigGetSnapshotConfig(ctx context.Context, request *NodesLxcSnapshotConfigGetSnapshotConfigRequest) (*NodesLxcSnapshotConfigGetSnapshotConfigResponse, error) {

	method := "GET"
	path := "/nodes/{node}/lxc/{vmid}/snapshot/{snapname}/config"

	var response NodesLxcSnapshotConfigGetSnapshotConfigResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
