// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type PoolsCreatePoolRequest struct {
	Comment *string `json:"comment,omitempty"` //
	Poolid  string  `json:"poolid,omitempty"`  //
}

type PoolsCreatePoolResponse struct{}

// Create new pool.
// https://pve.proxmox.com/pve-docs/api-viewer/#/pools
func (c *Client) PoolsCreatePool(ctx context.Context, request *PoolsCreatePoolRequest) (*PoolsCreatePoolResponse, error) {

	method := "POST"
	path := "/pools"

	var response PoolsCreatePoolResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
