// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessTfaListTfaRequest interface{}

// TFA Entry.
type AccessTfaListTfaResponseItemEntriesItem struct {
	Created     int64  `json:"created,omitempty"`     // Creation time of this entry as unix epoch.
	Description string `json:"description,omitempty"` // User chosen description for this entry.
	Enable      *bool  `json:"enable,omitempty"`      // Whether this TFA entry is currently enabled.
	Id          string `json:"id,omitempty"`          // The id used to reference this entry.
	Type        string `json:"type,omitempty"`        // TFA Entry Type.
}

type AccessTfaListTfaResponseItem struct {
	Entries []AccessTfaListTfaResponseItemEntriesItem `json:"entries,omitempty"` //
	Userid  string                                    `json:"userid,omitempty"`  // User this entry belongs to.
}

// The list tuples of user and TFA entries.
type AccessTfaListTfaResponse []AccessTfaListTfaResponseItem

// List TFA configurations of users.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/tfa
func (c *Client) AccessTfaListTfa(ctx context.Context, request *AccessTfaListTfaRequest) (*AccessTfaListTfaResponse, error) {

	method := "GET"
	path := "/access/tfa"

	var response AccessTfaListTfaResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
