// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnControllersDeleteRequest struct {
	Controller string `json:"controller,omitempty"` // The SDN controller object identifier.
}

type ClusterSdnControllersDeleteResponse struct{}

// Delete sdn controller object configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/controllers/{controller}
func (c *Client) ClusterSdnControllersDelete(ctx context.Context, request *ClusterSdnControllersDeleteRequest) (*ClusterSdnControllersDeleteResponse, error) {

	method := "DELETE"
	path := "/cluster/sdn/controllers/{controller}"

	var response ClusterSdnControllersDeleteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
