// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type PoolsReadPoolRequest struct {
	Poolid string  `query:"poolid,omitempty"` //
	Type   *string `query:"type,omitempty"`   //
}

type PoolsReadPoolResponseMembersItem struct {
	Id      string  `json:"id,omitempty"`      //
	Node    string  `json:"node,omitempty"`    //
	Storage *string `json:"storage,omitempty"` //
	Type    string  `json:"type,omitempty"`    //
	Vmid    *int64  `json:"vmid,omitempty"`    //
}

type PoolsReadPoolResponse struct {
	Comment *string                            `json:"comment,omitempty"` //
	Members []PoolsReadPoolResponseMembersItem `json:"members,omitempty"` //
}

// Get pool configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/pools/{poolid}
func (c *Client) PoolsReadPool(ctx context.Context, request *PoolsReadPoolRequest) (*PoolsReadPoolResponse, error) {

	method := "GET"
	path := "/pools/{poolid}"

	var response PoolsReadPoolResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
