// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDisksZfsCreateRequest struct {
	AddStorage  *bool   `json:"add_storage,omitempty"`  // Configure storage using the zpool.
	Ashift      *int64  `json:"ashift,omitempty"`       // Pool sector size exponent.
	Compression *string `json:"compression,omitempty"`  // The compression algorithm to use.
	Devices     string  `json:"devices,omitempty"`      // The block devices you want to create the zpool on.
	DraidConfig *string `json:"draid-config,omitempty"` //
	Name        string  `json:"name,omitempty"`         // The storage identifier.
	Node        string  `json:"node,omitempty"`         // The cluster node name.
	Raidlevel   string  `json:"raidlevel,omitempty"`    // The RAID level to use.
}

type NodesDisksZfsCreateResponse string

// Create a ZFS pool.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/disks/zfs
func (c *Client) NodesDisksZfsCreate(ctx context.Context, request *NodesDisksZfsCreateRequest) (*NodesDisksZfsCreateResponse, error) {

	method := "POST"
	path := "/nodes/{node}/disks/zfs"

	var response NodesDisksZfsCreateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
