// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesWakeonlanWakeonlanRequest struct {
	Node string `json:"node,omitempty"` // target node for wake on LAN packet
}

// MAC address used to assemble the WoL magic packet.
type NodesWakeonlanWakeonlanResponse string

// Try to wake a node via 'wake on LAN' network packet.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/wakeonlan
func (c *Client) NodesWakeonlanWakeonlan(ctx context.Context, request *NodesWakeonlanWakeonlanRequest) (*NodesWakeonlanWakeonlanResponse, error) {

	method := "POST"
	path := "/nodes/{node}/wakeonlan"

	var response NodesWakeonlanWakeonlanResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
