// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterHaIndexRequest interface{}

type ClusterHaIndexResponse []ClusterHaIndexResponseItem

type ClusterHaIndexResponseItem struct {
	Id string `json:"id,omitempty"` //
}

// Directory index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha
func (c *Client) ClusterHaIndex(ctx context.Context, request *ClusterHaIndexRequest) (*ClusterHaIndexResponse, error) {

	method := "GET"
	path := "/cluster/ha"

	var response ClusterHaIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
