// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentSetUserPasswordSetUserPasswordRequest struct {
	Crypted  *bool  `json:"crypted,omitempty"`  // set to 1 if the password has already been passed through crypt()
	Node     string `json:"node,omitempty"`     // The cluster node name.
	Password string `json:"password,omitempty"` // The new password.
	Username string `json:"username,omitempty"` // The user to set the password for.
	Vmid     int64  `json:"vmid,omitempty"`     // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentSetUserPasswordSetUserPasswordResponse interface{}

// Sets the password for the given user to the given password
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/set-user-password
func (c *Client) NodesQemuAgentSetUserPasswordSetUserPassword(ctx context.Context, request *NodesQemuAgentSetUserPasswordSetUserPasswordRequest) (*NodesQemuAgentSetUserPasswordSetUserPasswordResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent/set-user-password"

	var response NodesQemuAgentSetUserPasswordSetUserPasswordResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
