// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephStopStopRequest struct {
	Node    string  `json:"node,omitempty"`    // The cluster node name.
	Service *string `json:"service,omitempty"` // Ceph service name.
}

type NodesCephStopStopResponse string

// Stop ceph services.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/stop
func (c *Client) NodesCephStopStop(ctx context.Context, request *NodesCephStopStopRequest) (*NodesCephStopStopResponse, error) {

	method := "POST"
	path := "/nodes/{node}/ceph/stop"

	var response NodesCephStopStopResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
