// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesNetworkNetworkConfigRequest struct {
	Iface string `query:"iface,omitempty"` // Network interface name.
	Node  string `query:"node,omitempty"`  // The cluster node name.
}

type NodesNetworkNetworkConfigResponse struct {
	Method string `json:"method,omitempty"` //
	Type   string `json:"type,omitempty"`   //
}

// Read network device configuration
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/network/{iface}
func (c *Client) NodesNetworkNetworkConfig(ctx context.Context, request *NodesNetworkNetworkConfigRequest) (*NodesNetworkNetworkConfigResponse, error) {

	method := "GET"
	path := "/nodes/{node}/network/{iface}"

	var response NodesNetworkNetworkConfigResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
