// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnVnetsSubnetsReadRequest struct {
	Pending *bool  `query:"pending,omitempty"` // Display pending config.
	Running *bool  `query:"running,omitempty"` // Display running config.
	Subnet  string `query:"subnet,omitempty"`  // The SDN subnet object identifier.
	Vnet    string `query:"vnet,omitempty"`    // The SDN vnet object identifier.
}

type ClusterSdnVnetsSubnetsReadResponse interface{}

// Read sdn subnet configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/vnets/{vnet}/subnets/{subnet}
func (c *Client) ClusterSdnVnetsSubnetsRead(ctx context.Context, request *ClusterSdnVnetsSubnetsReadRequest) (*ClusterSdnVnetsSubnetsReadResponse, error) {

	method := "GET"
	path := "/cluster/sdn/vnets/{vnet}/subnets/{subnet}"

	var response ClusterSdnVnetsSubnetsReadResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
