// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesTasksStatusReadTaskStatusRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Upid string `query:"upid,omitempty"` // The task's unique ID.
}

type NodesTasksStatusReadTaskStatusResponse struct {
	Exitstatus *string `json:"exitstatus,omitempty"` //
	Id         string  `json:"id,omitempty"`         //
	Node       string  `json:"node,omitempty"`       //
	Pid        int64   `json:"pid,omitempty"`        //
	Starttime  float64 `json:"starttime,omitempty"`  //
	Status     string  `json:"status,omitempty"`     //
	Type       string  `json:"type,omitempty"`       //
	Upid       string  `json:"upid,omitempty"`       //
	User       string  `json:"user,omitempty"`       //
}

// Read task status.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/tasks/{upid}/status
func (c *Client) NodesTasksStatusReadTaskStatus(ctx context.Context, request *NodesTasksStatusReadTaskStatusRequest) (*NodesTasksStatusReadTaskStatusResponse, error) {

	method := "GET"
	path := "/nodes/{node}/tasks/{upid}/status"

	var response NodesTasksStatusReadTaskStatusResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
