// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessDomainsDeleteRequest struct {
	Realm string `json:"realm,omitempty"` // Authentication domain ID
}

type AccessDomainsDeleteResponse struct{}

// Delete an authentication server.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/domains/{realm}
func (c *Client) AccessDomainsDelete(ctx context.Context, request *AccessDomainsDeleteRequest) (*AccessDomainsDeleteResponse, error) {

	method := "DELETE"
	path := "/access/domains/{realm}"

	var response AccessDomainsDeleteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
