// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDisksSmartSmartRequest struct {
	Disk       string `query:"disk,omitempty"`       // Block device name
	Healthonly *bool  `query:"healthonly,omitempty"` // If true returns only the health status
	Node       string `query:"node,omitempty"`       // The cluster node name.
}

type NodesDisksSmartSmartResponse struct {
	Attributes *[]interface{} `json:"attributes,omitempty"` //
	Health     string         `json:"health,omitempty"`     //
	Text       *string        `json:"text,omitempty"`       //
	Type       *string        `json:"type,omitempty"`       //
}

// Get SMART Health of a disk.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/disks/smart
func (c *Client) NodesDisksSmartSmart(ctx context.Context, request *NodesDisksSmartSmartRequest) (*NodesDisksSmartSmartResponse, error) {

	method := "GET"
	path := "/nodes/{node}/disks/smart"

	var response NodesDisksSmartSmartResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
