// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterConfigNodesDelnodeRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
}

type ClusterConfigNodesDelnodeResponse struct{}

// Removes a node from the cluster configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/config/nodes/{node}
func (c *Client) ClusterConfigNodesDelnode(ctx context.Context, request *ClusterConfigNodesDelnodeRequest) (*ClusterConfigNodesDelnodeResponse, error) {

	method := "DELETE"
	path := "/cluster/config/nodes/{node}"

	var response ClusterConfigNodesDelnodeResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
