// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterAcmeAccountRegisterAccountRequest struct {
	Contact   string  `json:"contact,omitempty"`   // Contact email addresses.
	Directory *string `json:"directory,omitempty"` // URL of ACME CA directory endpoint.
	Name      *string `json:"name,omitempty"`      // ACME account config file name.
	TosUrl    *string `json:"tos_url,omitempty"`   // URL of CA TermsOfService - setting this indicates agreement.
}

type ClusterAcmeAccountRegisterAccountResponse string

// Register a new ACME account with CA.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/acme/account
func (c *Client) ClusterAcmeAccountRegisterAccount(ctx context.Context, request *ClusterAcmeAccountRegisterAccountRequest) (*ClusterAcmeAccountRegisterAccountResponse, error) {

	method := "POST"
	path := "/cluster/acme/account"

	var response ClusterAcmeAccountRegisterAccountResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
