// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns the list of Qemu Agent commands
type NodesQemuAgentIndexResponse []NodesQemuAgentIndexResponseItem

type NodesQemuAgentIndexResponseItem struct {
}

// Qemu Agent command index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent
func (c *Client) NodesQemuAgentIndex(ctx context.Context, request *NodesQemuAgentIndexRequest) (*NodesQemuAgentIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/agent"

	var response NodesQemuAgentIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
