// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuPendingVmPendingRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesQemuPendingVmPendingResponse []NodesQemuPendingVmPendingResponseItem

type NodesQemuPendingVmPendingResponseItem struct {
	Delete  *int64  `json:"delete,omitempty"`  // Indicates a pending delete request if present and not 0. The value 2 indicates a force-delete request.
	Key     string  `json:"key,omitempty"`     // Configuration option name.
	Pending *string `json:"pending,omitempty"` // Pending value.
	Value   *string `json:"value,omitempty"`   // Current value.
}

// Get the virtual machine configuration with both current and pending values.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/pending
func (c *Client) NodesQemuPendingVmPending(ctx context.Context, request *NodesQemuPendingVmPendingRequest) (*NodesQemuPendingVmPendingResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/pending"

	var response NodesQemuPendingVmPendingResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
