// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterAcmeDirectoriesGetDirectoriesRequest interface{}

type ClusterAcmeDirectoriesGetDirectoriesResponseItem struct {
	Name string `json:"name,omitempty"` //
	Url  string `json:"url,omitempty"`  // URL of ACME CA directory endpoint.
}

type ClusterAcmeDirectoriesGetDirectoriesResponse []ClusterAcmeDirectoriesGetDirectoriesResponseItem

// Get named known ACME directory endpoints.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/acme/directories
func (c *Client) ClusterAcmeDirectoriesGetDirectories(ctx context.Context, request *ClusterAcmeDirectoriesGetDirectoriesRequest) (*ClusterAcmeDirectoriesGetDirectoriesResponse, error) {

	method := "GET"
	path := "/cluster/acme/directories"

	var response ClusterAcmeDirectoriesGetDirectoriesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
