// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterConfigApiversionJoinApiVersionRequest interface{}

// Cluster Join API version, currently 1
type ClusterConfigApiversionJoinApiVersionResponse int64

// Return the version of the cluster join API available on this node.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/config/apiversion
func (c *Client) ClusterConfigApiversionJoinApiVersion(ctx context.Context, request *ClusterConfigApiversionJoinApiVersionRequest) (*ClusterConfigApiversionJoinApiVersionResponse, error) {

	method := "GET"
	path := "/cluster/config/apiversion"

	var response ClusterConfigApiversionJoinApiVersionResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
