// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuUnlinkUnlinkRequest struct {
	Force  *bool  `json:"force,omitempty"`  // Force physical removal. Without this, we simple remove the disk from the config file and create an additional configuration entry called 'unused[n]', which contains the volume ID. Unlink of unused[n] always cause physical removal.
	Idlist string `json:"idlist,omitempty"` // A list of disk IDs you want to delete.
	Node   string `json:"node,omitempty"`   // The cluster node name.
	Vmid   int64  `json:"vmid,omitempty"`   // The (unique) ID of the VM.
}

type NodesQemuUnlinkUnlinkResponse struct{}

// Unlink/delete disk images.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/unlink
func (c *Client) NodesQemuUnlinkUnlink(ctx context.Context, request *NodesQemuUnlinkUnlinkRequest) (*NodesQemuUnlinkUnlinkResponse, error) {

	method := "PUT"
	path := "/nodes/{node}/qemu/{vmid}/unlink"

	var response NodesQemuUnlinkUnlinkResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
