// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallIpsetDeleteIpsetRequest struct {
	Force *bool  `json:"force,omitempty"` // Delete all members of the IPSet, if there are any.
	Name  string `json:"name,omitempty"`  // IP set name.
}

type ClusterFirewallIpsetDeleteIpsetResponse struct{}

// Delete IPSet
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/ipset/{name}
func (c *Client) ClusterFirewallIpsetDeleteIpset(ctx context.Context, request *ClusterFirewallIpsetDeleteIpsetRequest) (*ClusterFirewallIpsetDeleteIpsetResponse, error) {

	method := "DELETE"
	path := "/cluster/firewall/ipset/{name}"

	var response ClusterFirewallIpsetDeleteIpsetResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
