// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesHostsGetEtcHostsRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesHostsGetEtcHostsResponse struct {
	Data   string  `json:"data,omitempty"`   // The content of /etc/hosts.
	Digest *string `json:"digest,omitempty"` // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
}

// Get the content of /etc/hosts.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/hosts
func (c *Client) NodesHostsGetEtcHosts(ctx context.Context, request *NodesHostsGetEtcHostsRequest) (*NodesHostsGetEtcHostsResponse, error) {

	method := "GET"
	path := "/nodes/{node}/hosts"

	var response NodesHostsGetEtcHostsResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
