// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterReplicationCreateRequest struct {
	Comment   *string  `json:"comment,omitempty"`    // Description.
	Disable   *bool    `json:"disable,omitempty"`    // Flag to disable/deactivate the entry.
	Id        string   `json:"id,omitempty"`         // Replication Job ID. The ID is composed of a Guest ID and a job number, separated by a hyphen, i.e. '<GUEST>-<JOBNUM>'.
	Rate      *float64 `json:"rate,omitempty"`       // Rate limit in mbps (megabytes per second) as floating point number.
	RemoveJob *string  `json:"remove_job,omitempty"` // Mark the replication job for removal. The job will remove all local replication snapshots. When set to 'full', it also tries to remove replicated volumes on the target. The job then removes itself from the configuration file.
	Schedule  *string  `json:"schedule,omitempty"`   // Storage replication schedule. The format is a subset of `systemd` calendar events.
	Source    *string  `json:"source,omitempty"`     // For internal use, to detect if the guest was stolen.
	Target    string   `json:"target,omitempty"`     // Target node.
	Type      string   `json:"type,omitempty"`       // Section type.
}

type ClusterReplicationCreateResponse struct{}

// Create a new replication job
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/replication
func (c *Client) ClusterReplicationCreate(ctx context.Context, request *ClusterReplicationCreateRequest) (*ClusterReplicationCreateResponse, error) {

	method := "POST"
	path := "/cluster/replication"

	var response ClusterReplicationCreateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
