// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephMdsCreatemdsRequest struct {
	Hotstandby *bool   `json:"hotstandby,omitempty"` // Determines whether a ceph-mds daemon should poll and replay the log of an active MDS. Faster switch on MDS failure, but needs more idle resources.
	Name       *string `json:"name,omitempty"`       // The ID for the mds, when omitted the same as the nodename
	Node       string  `json:"node,omitempty"`       // The cluster node name.
}

type NodesCephMdsCreatemdsResponse string

// Create Ceph Metadata Server (MDS)
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/mds/{name}
func (c *Client) NodesCephMdsCreatemds(ctx context.Context, request *NodesCephMdsCreatemdsRequest) (*NodesCephMdsCreatemdsResponse, error) {

	method := "POST"
	path := "/nodes/{node}/ceph/mds/{name}"

	var response NodesCephMdsCreatemdsResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
