// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallAliasesReadAliasRequest struct {
	Name string `query:"name,omitempty"` // Alias name.
}

type ClusterFirewallAliasesReadAliasResponse interface{}

// Read alias.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/aliases/{name}
func (c *Client) ClusterFirewallAliasesReadAlias(ctx context.Context, request *ClusterFirewallAliasesReadAliasRequest) (*ClusterFirewallAliasesReadAliasResponse, error) {

	method := "GET"
	path := "/cluster/firewall/aliases/{name}"

	var response ClusterFirewallAliasesReadAliasResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
