// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentAgentRequest struct {
	Command string `json:"command,omitempty"` // The QGA command.
	Node    string `json:"node,omitempty"`    // The cluster node name.
	Vmid    int64  `json:"vmid,omitempty"`    // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentAgentResponse interface{}

// Execute Qemu Guest Agent commands.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent
func (c *Client) NodesQemuAgentAgent(ctx context.Context, request *NodesQemuAgentAgentRequest) (*NodesQemuAgentAgentResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent"

	var response NodesQemuAgentAgentResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
