// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterResourcesResourcesRequest struct {
	Type *string `query:"type,omitempty"` //
}

type ClusterResourcesResourcesResponseItem struct {
	CgroupMode *int64   `json:"cgroup-mode,omitempty"` // The cgroup mode the node operates under (when type == node).
	Content    *string  `json:"content,omitempty"`     // Allowed storage content types (when type == storage).
	Cpu        *float64 `json:"cpu,omitempty"`         // CPU utilization (when type in node,qemu,lxc).
	Disk       *int64   `json:"disk,omitempty"`        // Used disk space in bytes (when type in storage), used root image spave for VMs (type in qemu,lxc).
	Hastate    *string  `json:"hastate,omitempty"`     // HA service status (for HA managed VMs).
	Id         string   `json:"id,omitempty"`          //
	Level      *string  `json:"level,omitempty"`       // Support level (when type == node).
	Maxcpu     *float64 `json:"maxcpu,omitempty"`      // Number of available CPUs (when type in node,qemu,lxc).
	Maxdisk    *int64   `json:"maxdisk,omitempty"`     // Storage size in bytes (when type in storage), root image size for VMs (type in qemu,lxc).
	Maxmem     *int64   `json:"maxmem,omitempty"`      // Number of available memory in bytes (when type in node,qemu,lxc).
	Mem        *int64   `json:"mem,omitempty"`         // Used memory in bytes (when type in node,qemu,lxc).
	Name       *string  `json:"name,omitempty"`        // Name of the resource.
	Node       *string  `json:"node,omitempty"`        // The cluster node name (when type in node,storage,qemu,lxc).
	Plugintype *string  `json:"plugintype,omitempty"`  // More specific type, if available.
	Pool       *string  `json:"pool,omitempty"`        // The pool name (when type in pool,qemu,lxc).
	Status     *string  `json:"status,omitempty"`      // Resource type dependent status.
	Storage    *string  `json:"storage,omitempty"`     // The storage identifier (when type == storage).
	Type       string   `json:"type,omitempty"`        // Resource type.
	Uptime     *int64   `json:"uptime,omitempty"`      // Node uptime in seconds (when type in node,qemu,lxc).
	Vmid       *int64   `json:"vmid,omitempty"`        // The numerical vmid (when type in qemu,lxc).
}

type ClusterResourcesResourcesResponse []ClusterResourcesResourcesResponseItem

// Resources index (cluster wide).
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/resources
func (c *Client) ClusterResourcesResources(ctx context.Context, request *ClusterResourcesResourcesRequest) (*ClusterResourcesResourcesResponse, error) {

	method := "GET"
	path := "/cluster/resources"

	var response ClusterResourcesResourcesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
