// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentGetTimeGetTimeRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentGetTimeGetTimeResponse interface{}

// Execute get-time.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/get-time
func (c *Client) NodesQemuAgentGetTimeGetTime(ctx context.Context, request *NodesQemuAgentGetTimeGetTimeRequest) (*NodesQemuAgentGetTimeGetTimeResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/agent/get-time"

	var response NodesQemuAgentGetTimeGetTimeResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
