// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentShutdownShutdownRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Vmid int64  `json:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentShutdownShutdownResponse interface{}

// Execute shutdown.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/shutdown
func (c *Client) NodesQemuAgentShutdownShutdown(ctx context.Context, request *NodesQemuAgentShutdownShutdownRequest) (*NodesQemuAgentShutdownShutdownResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent/shutdown"

	var response NodesQemuAgentShutdownShutdownResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
