// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesVzdumpExtractconfigExtractconfigRequest struct {
	Node   string `query:"node,omitempty"`   // The cluster node name.
	Volume string `query:"volume,omitempty"` // Volume identifier
}

type NodesVzdumpExtractconfigExtractconfigResponse string

// Extract configuration from vzdump backup archive.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/vzdump/extractconfig
func (c *Client) NodesVzdumpExtractconfigExtractconfig(ctx context.Context, request *NodesVzdumpExtractconfigExtractconfigRequest) (*NodesVzdumpExtractconfigExtractconfigResponse, error) {

	method := "GET"
	path := "/nodes/{node}/vzdump/extractconfig"

	var response NodesVzdumpExtractconfigExtractconfigResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
