// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcFirewallIpsetDeleteIpsetRequest struct {
	Force *bool  `json:"force,omitempty"` // Delete all members of the IPSet, if there are any.
	Name  string `json:"name,omitempty"`  // IP set name.
	Node  string `json:"node,omitempty"`  // The cluster node name.
	Vmid  int64  `json:"vmid,omitempty"`  // The (unique) ID of the VM.
}

type NodesLxcFirewallIpsetDeleteIpsetResponse struct{}

// Delete IPSet
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/firewall/ipset/{name}
func (c *Client) NodesLxcFirewallIpsetDeleteIpset(ctx context.Context, request *NodesLxcFirewallIpsetDeleteIpsetRequest) (*NodesLxcFirewallIpsetDeleteIpsetResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/lxc/{vmid}/firewall/ipset/{name}"

	var response NodesLxcFirewallIpsetDeleteIpsetResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
