// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuSnapshotRollbackRollbackRequest struct {
	Node     string `json:"node,omitempty"`     // The cluster node name.
	Snapname string `json:"snapname,omitempty"` // The name of the snapshot.
	Start    *bool  `json:"start,omitempty"`    // Whether the VM should get started after rolling back successfully
	Vmid     int64  `json:"vmid,omitempty"`     // The (unique) ID of the VM.
}

// the task ID.
type NodesQemuSnapshotRollbackRollbackResponse string

// Rollback VM state to specified snapshot.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/snapshot/{snapname}/rollback
func (c *Client) NodesQemuSnapshotRollbackRollback(ctx context.Context, request *NodesQemuSnapshotRollbackRollbackRequest) (*NodesQemuSnapshotRollbackRollbackResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/snapshot/{snapname}/rollback"

	var response NodesQemuSnapshotRollbackRollbackResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
