// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesTasksStopTaskRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Upid string `json:"upid,omitempty"` //
}

type NodesTasksStopTaskResponse struct{}

// Stop a task.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/tasks/{upid}
func (c *Client) NodesTasksStopTask(ctx context.Context, request *NodesTasksStopTaskRequest) (*NodesTasksStopTaskResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/tasks/{upid}"

	var response NodesTasksStopTaskResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
