// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcFirewallRulesGetRuleRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Pos  *int64 `query:"pos,omitempty"`  // Update rule at position <pos>.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesLxcFirewallRulesGetRuleResponse struct {
	Action    string  `json:"action,omitempty"`    //
	Comment   *string `json:"comment,omitempty"`   //
	Dest      *string `json:"dest,omitempty"`      //
	Dport     *string `json:"dport,omitempty"`     //
	Enable    *int64  `json:"enable,omitempty"`    //
	IcmpType  *string `json:"icmp-type,omitempty"` //
	Iface     *string `json:"iface,omitempty"`     //
	Ipversion *int64  `json:"ipversion,omitempty"` //
	Log       *string `json:"log,omitempty"`       // Log level for firewall rule
	Macro     *string `json:"macro,omitempty"`     //
	Pos       int64   `json:"pos,omitempty"`       //
	Proto     *string `json:"proto,omitempty"`     //
	Source    *string `json:"source,omitempty"`    //
	Sport     *string `json:"sport,omitempty"`     //
	Type      string  `json:"type,omitempty"`      //
}

// Get single rule data.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/firewall/rules/{pos}
func (c *Client) NodesLxcFirewallRulesGetRule(ctx context.Context, request *NodesLxcFirewallRulesGetRuleRequest) (*NodesLxcFirewallRulesGetRuleResponse, error) {

	method := "GET"
	path := "/nodes/{node}/lxc/{vmid}/firewall/rules/{pos}"

	var response NodesLxcFirewallRulesGetRuleResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
