// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesAptChangelogChangelogRequest struct {
	Name    string  `query:"name,omitempty"`    // Package name.
	Node    string  `query:"node,omitempty"`    // The cluster node name.
	Version *string `query:"version,omitempty"` // Package version.
}

type NodesAptChangelogChangelogResponse string

// Get package changelogs.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/apt/changelog
func (c *Client) NodesAptChangelogChangelog(ctx context.Context, request *NodesAptChangelogChangelogRequest) (*NodesAptChangelogChangelogResponse, error) {

	method := "GET"
	path := "/nodes/{node}/apt/changelog"

	var response NodesAptChangelogChangelogResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
