// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterMetricsServerServerIndexRequest interface{}

type ClusterMetricsServerServerIndexResponseItem struct {
	Disable bool   `json:"disable,omitempty"` // Flag to disable the plugin.
	Id      string `json:"id,omitempty"`      // The ID of the entry.
	Port    int64  `json:"port,omitempty"`    // Server network port
	Server  string `json:"server,omitempty"`  // Server dns name or IP address
	Type    string `json:"type,omitempty"`    // Plugin type.
}

type ClusterMetricsServerServerIndexResponse []ClusterMetricsServerServerIndexResponseItem

// List configured metric servers.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/metrics/server
func (c *Client) ClusterMetricsServerServerIndex(ctx context.Context, request *ClusterMetricsServerServerIndexRequest) (*ClusterMetricsServerServerIndexResponse, error) {

	method := "GET"
	path := "/cluster/metrics/server"

	var response ClusterMetricsServerServerIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
