// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcFirewallAliasesRemoveAliasRequest struct {
	Digest *string `json:"digest,omitempty"` // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Name   string  `json:"name,omitempty"`   // Alias name.
	Node   string  `json:"node,omitempty"`   // The cluster node name.
	Vmid   int64   `json:"vmid,omitempty"`   // The (unique) ID of the VM.
}

type NodesLxcFirewallAliasesRemoveAliasResponse struct{}

// Remove IP or Network alias.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/firewall/aliases/{name}
func (c *Client) NodesLxcFirewallAliasesRemoveAlias(ctx context.Context, request *NodesLxcFirewallAliasesRemoveAliasRequest) (*NodesLxcFirewallAliasesRemoveAliasResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/lxc/{vmid}/firewall/aliases/{name}"

	var response NodesLxcFirewallAliasesRemoveAliasResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
