// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuStatusResumeVmResumeRequest struct {
	Nocheck  *bool  `json:"nocheck,omitempty"`  //
	Node     string `json:"node,omitempty"`     // The cluster node name.
	Skiplock *bool  `json:"skiplock,omitempty"` // Ignore locks - only root is allowed to use this option.
	Vmid     int64  `json:"vmid,omitempty"`     // The (unique) ID of the VM.
}

type NodesQemuStatusResumeVmResumeResponse string

// Resume virtual machine.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/status/resume
func (c *Client) NodesQemuStatusResumeVmResume(ctx context.Context, request *NodesQemuStatusResumeVmResumeRequest) (*NodesQemuStatusResumeVmResumeResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/status/resume"

	var response NodesQemuStatusResumeVmResumeResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
