// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephPoolsDestroypoolRequest struct {
	Force           *bool  `json:"force,omitempty"`            // If true, destroys pool even if in use
	Name            string `json:"name,omitempty"`             // The name of the pool. It must be unique.
	Node            string `json:"node,omitempty"`             // The cluster node name.
	RemoveEcprofile *bool  `json:"remove_ecprofile,omitempty"` // Remove the erasure code profile. Defaults to true, if applicable.
	RemoveStorages  *bool  `json:"remove_storages,omitempty"`  // Remove all pveceph-managed storages configured for this pool
}

type NodesCephPoolsDestroypoolResponse string

// Destroy pool
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/pools/{name}
func (c *Client) NodesCephPoolsDestroypool(ctx context.Context, request *NodesCephPoolsDestroypoolRequest) (*NodesCephPoolsDestroypoolResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/ceph/pools/{name}"

	var response NodesCephPoolsDestroypoolResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
