// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallAliasesUpdateAliasRequest struct {
	Cidr    string  `json:"cidr,omitempty"`    // Network/IP specification in CIDR format.
	Comment *string `json:"comment,omitempty"` //
	Digest  *string `json:"digest,omitempty"`  // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Name    string  `json:"name,omitempty"`    // Alias name.
	Rename  *string `json:"rename,omitempty"`  // Rename an existing alias.
}

type ClusterFirewallAliasesUpdateAliasResponse struct{}

// Update IP or Network alias.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/aliases/{name}
func (c *Client) ClusterFirewallAliasesUpdateAlias(ctx context.Context, request *ClusterFirewallAliasesUpdateAliasRequest) (*ClusterFirewallAliasesUpdateAliasResponse, error) {

	method := "PUT"
	path := "/cluster/firewall/aliases/{name}"

	var response ClusterFirewallAliasesUpdateAliasResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
