// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephStartStartRequest struct {
	Node    string  `json:"node,omitempty"`    // The cluster node name.
	Service *string `json:"service,omitempty"` // Ceph service name.
}

type NodesCephStartStartResponse string

// Start ceph services.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/start
func (c *Client) NodesCephStartStart(ctx context.Context, request *NodesCephStartStartRequest) (*NodesCephStartStartResponse, error) {

	method := "POST"
	path := "/nodes/{node}/ceph/start"

	var response NodesCephStartStartResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
