// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessDomainsIndexRequest interface{}

type AccessDomainsIndexResponse []AccessDomainsIndexResponseItem

type AccessDomainsIndexResponseItem struct {
	Comment *string `json:"comment,omitempty"` // A comment. The GUI use this text when you select a domain (Realm) on the login window.
	Realm   string  `json:"realm,omitempty"`   //
	Tfa     *string `json:"tfa,omitempty"`     // Two-factor authentication provider.
	Type    string  `json:"type,omitempty"`    //
}

// Authentication domain index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/domains
func (c *Client) AccessDomainsIndex(ctx context.Context, request *AccessDomainsIndexRequest) (*AccessDomainsIndexResponse, error) {

	method := "GET"
	path := "/access/domains"

	var response AccessDomainsIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
