// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuFeatureVmFeatureRequest struct {
	Feature  string  `query:"feature,omitempty"`  // Feature to check.
	Node     string  `query:"node,omitempty"`     // The cluster node name.
	Snapname *string `query:"snapname,omitempty"` // The name of the snapshot.
	Vmid     int64   `query:"vmid,omitempty"`     // The (unique) ID of the VM.
}

type NodesQemuFeatureVmFeatureResponse struct {
	HasFeature bool                                         `json:"hasFeature,omitempty"` //
	Nodes      []NodesQemuFeatureVmFeatureResponseNodesItem `json:"nodes,omitempty"`      //
}

type NodesQemuFeatureVmFeatureResponseNodesItem string

// Check if feature for virtual machine is available.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/feature
func (c *Client) NodesQemuFeatureVmFeature(ctx context.Context, request *NodesQemuFeatureVmFeatureRequest) (*NodesQemuFeatureVmFeatureResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/feature"

	var response NodesQemuFeatureVmFeatureResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
