// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuCloudinitCloudinitPendingRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesQemuCloudinitCloudinitPendingResponseItem struct {
	Key string  `json:"key,omitempty"` // Configuration option name.
	New *string `json:"new,omitempty"` // The new pending value.
	Old *string `json:"old,omitempty"` // Value as it was used to generate the current cloudinit image.
}

type NodesQemuCloudinitCloudinitPendingResponse []NodesQemuCloudinitCloudinitPendingResponseItem

// Get the cloudinit configuration with both current and pending values.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/cloudinit
func (c *Client) NodesQemuCloudinitCloudinitPending(ctx context.Context, request *NodesQemuCloudinitCloudinitPendingRequest) (*NodesQemuCloudinitCloudinitPendingResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/cloudinit"

	var response NodesQemuCloudinitCloudinitPendingResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
