// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuRrdRrdRequest struct {
	Cf        *string `query:"cf,omitempty"`        // The RRD consolidation function
	Ds        string  `query:"ds,omitempty"`        // The list of datasources you want to display.
	Node      string  `query:"node,omitempty"`      // The cluster node name.
	Timeframe string  `query:"timeframe,omitempty"` // Specify the time frame you are interested in.
	Vmid      int64   `query:"vmid,omitempty"`      // The (unique) ID of the VM.
}

type NodesQemuRrdRrdResponse struct {
	Filename string `json:"filename,omitempty"` //
}

// Read VM RRD statistics (returns PNG)
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/rrd
func (c *Client) NodesQemuRrdRrd(ctx context.Context, request *NodesQemuRrdRrdRequest) (*NodesQemuRrdRrdResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/rrd"

	var response NodesQemuRrdRrdResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
