// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterBackupIndexRequest interface{}

type ClusterBackupIndexResponseItem struct {
	Id string `json:"id,omitempty"` // The job ID.
}

type ClusterBackupIndexResponse []ClusterBackupIndexResponseItem

// List vzdump backup schedule.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/backup
func (c *Client) ClusterBackupIndex(ctx context.Context, request *ClusterBackupIndexRequest) (*ClusterBackupIndexResponse, error) {

	method := "GET"
	path := "/cluster/backup"

	var response ClusterBackupIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
