// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephMdsDestroymdsRequest struct {
	Name string `json:"name,omitempty"` // The name (ID) of the mds
	Node string `json:"node,omitempty"` // The cluster node name.
}

type NodesCephMdsDestroymdsResponse string

// Destroy Ceph Metadata Server
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/mds/{name}
func (c *Client) NodesCephMdsDestroymds(ctx context.Context, request *NodesCephMdsDestroymdsRequest) (*NodesCephMdsDestroymdsResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/ceph/mds/{name}"

	var response NodesCephMdsDestroymdsResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
