// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesReplicationStatusRequest struct {
	Guest *int64 `query:"guest,omitempty"` // Only list replication jobs for this guest.
	Node  string `query:"node,omitempty"`  // The cluster node name.
}

type NodesReplicationStatusResponse []NodesReplicationStatusResponseItem

type NodesReplicationStatusResponseItem struct {
	Id string `json:"id,omitempty"` //
}

// List status of all replication jobs on this node.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/replication
func (c *Client) NodesReplicationStatus(ctx context.Context, request *NodesReplicationStatusRequest) (*NodesReplicationStatusResponse, error) {

	method := "GET"
	path := "/nodes/{node}/replication"

	var response NodesReplicationStatusResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
