// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallRulesDeleteRuleRequest struct {
	Digest *string `json:"digest,omitempty"` // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Pos    *int64  `json:"pos,omitempty"`    // Update rule at position <pos>.
}

type ClusterFirewallRulesDeleteRuleResponse struct{}

// Delete rule.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/rules/{pos}
func (c *Client) ClusterFirewallRulesDeleteRule(ctx context.Context, request *ClusterFirewallRulesDeleteRuleRequest) (*ClusterFirewallRulesDeleteRuleResponse, error) {

	method := "DELETE"
	path := "/cluster/firewall/rules/{pos}"

	var response ClusterFirewallRulesDeleteRuleResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
