// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterNextidNextidRequest struct {
	Vmid *int64 `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

// The next free VMID.
type ClusterNextidNextidResponse int64

// Get next free VMID. Pass a VMID to assert that its free (at time of check).
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/nextid
func (c *Client) ClusterNextidNextid(ctx context.Context, request *ClusterNextidNextidRequest) (*ClusterNextidNextidResponse, error) {

	method := "GET"
	path := "/cluster/nextid"

	var response ClusterNextidNextidResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
