// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterHaResourcesMigrateMigrateRequest struct {
	Node string `json:"node,omitempty"` // Target node.
	Sid  string `json:"sid,omitempty"`  // HA resource ID. This consists of a resource type followed by a resource specific name, separated with colon (example: vm:100 / ct:100). For virtual machines and containers, you can simply use the VM or CT id as a shortcut (example: 100).
}

type ClusterHaResourcesMigrateMigrateResponse struct{}

// Request resource migration (online) to another node.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha/resources/{sid}/migrate
func (c *Client) ClusterHaResourcesMigrateMigrate(ctx context.Context, request *ClusterHaResourcesMigrateMigrateRequest) (*ClusterHaResourcesMigrateMigrateResponse, error) {

	method := "POST"
	path := "/cluster/ha/resources/{sid}/migrate"

	var response ClusterHaResourcesMigrateMigrateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
