// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephOsdOutOutRequest struct {
	Node  string `json:"node,omitempty"`  // The cluster node name.
	Osdid int64  `json:"osdid,omitempty"` // OSD ID
}

type NodesCephOsdOutOutResponse struct{}

// ceph osd out
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/osd/{osdid}/out
func (c *Client) NodesCephOsdOutOut(ctx context.Context, request *NodesCephOsdOutOutRequest) (*NodesCephOsdOutOutResponse, error) {

	method := "POST"
	path := "/nodes/{node}/ceph/osd/{osdid}/out"

	var response NodesCephOsdOutOutResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
