// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesServicesStartServiceStartRequest struct {
	Node    string `json:"node,omitempty"`    // The cluster node name.
	Service string `json:"service,omitempty"` // Service ID
}

type NodesServicesStartServiceStartResponse string

// Start service.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/services/{service}/start
func (c *Client) NodesServicesStartServiceStart(ctx context.Context, request *NodesServicesStartServiceStartRequest) (*NodesServicesStartServiceStartResponse, error) {

	method := "POST"
	path := "/nodes/{node}/services/{service}/start"

	var response NodesServicesStartServiceStartResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
