// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterHaGroupsIndexRequest interface{}

type ClusterHaGroupsIndexResponse []ClusterHaGroupsIndexResponseItem

type ClusterHaGroupsIndexResponseItem struct {
	Group string `json:"group,omitempty"` //
}

// Get HA groups.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha/groups
func (c *Client) ClusterHaGroupsIndex(ctx context.Context, request *ClusterHaGroupsIndexRequest) (*ClusterHaGroupsIndexResponse, error) {

	method := "GET"
	path := "/cluster/ha/groups"

	var response ClusterHaGroupsIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
