// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcFirewallAliasesGetAliasesRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesLxcFirewallAliasesGetAliasesResponseItem struct {
	Cidr    string  `json:"cidr,omitempty"`    //
	Comment *string `json:"comment,omitempty"` //
	Digest  string  `json:"digest,omitempty"`  // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Name    string  `json:"name,omitempty"`    //
}

type NodesLxcFirewallAliasesGetAliasesResponse []NodesLxcFirewallAliasesGetAliasesResponseItem

// List aliases
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/firewall/aliases
func (c *Client) NodesLxcFirewallAliasesGetAliases(ctx context.Context, request *NodesLxcFirewallAliasesGetAliasesRequest) (*NodesLxcFirewallAliasesGetAliasesResponse, error) {

	method := "GET"
	path := "/nodes/{node}/lxc/{vmid}/firewall/aliases"

	var response NodesLxcFirewallAliasesGetAliasesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
