// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessTfaAddTfaEntryRequest struct {
	Challenge   *string `json:"challenge,omitempty"`   // When responding to a u2f challenge: the original challenge string
	Description *string `json:"description,omitempty"` // A description to distinguish multiple entries from one another
	Password    *string `json:"password,omitempty"`    // The current password.
	Totp        *string `json:"totp,omitempty"`        // A totp URI.
	Type        string  `json:"type,omitempty"`        // TFA Entry Type.
	Userid      string  `json:"userid,omitempty"`      // User ID
	Value       *string `json:"value,omitempty"`       // The current value for the provided totp URI, or a Webauthn/U2F challenge response
}

// A recovery entry.
type AccessTfaAddTfaEntryResponseRecoveryItem string

type AccessTfaAddTfaEntryResponse struct {
	Challenge *string                                     `json:"challenge,omitempty"` // When adding u2f entries, this contains a challenge the user must respond to in order to finish the registration.
	Id        string                                      `json:"id,omitempty"`        // The id of a newly added TFA entry.
	Recovery  *[]AccessTfaAddTfaEntryResponseRecoveryItem `json:"recovery,omitempty"`  // When adding recovery codes, this contains the list of codes to be displayed to the user
}

// Add a TFA entry for a user.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/tfa/{userid}
func (c *Client) AccessTfaAddTfaEntry(ctx context.Context, request *AccessTfaAddTfaEntryRequest) (*AccessTfaAddTfaEntryResponse, error) {

	method := "POST"
	path := "/access/tfa/{userid}"

	var response AccessTfaAddTfaEntryResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
