// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcFirewallIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesLxcFirewallIndexResponseItem struct {
}

type NodesLxcFirewallIndexResponse []NodesLxcFirewallIndexResponseItem

// Directory index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/firewall
func (c *Client) NodesLxcFirewallIndex(ctx context.Context, request *NodesLxcFirewallIndexRequest) (*NodesLxcFirewallIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/lxc/{vmid}/firewall"

	var response NodesLxcFirewallIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
