// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type VersionVersionRequest interface{}

type VersionVersionResponse struct {
	Console *string `json:"console,omitempty"` // The default console viewer to use.
	Release string  `json:"release,omitempty"` // The current Proxmox VE point release in `x.y` format.
	Repoid  string  `json:"repoid,omitempty"`  // The short git revision from which this version was build.
	Version string  `json:"version,omitempty"` // The full pve-manager package version of this node.
}

// API version details, including some parts of the global datacenter config.
// https://pve.proxmox.com/pve-docs/api-viewer/#/version
func (c *Client) VersionVersion(ctx context.Context, request *VersionVersionRequest) (*VersionVersionResponse, error) {

	method := "GET"
	path := "/version"

	var response VersionVersionResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
