// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterHaResourcesIndexRequest struct {
	Type *string `query:"type,omitempty"` // Only list resources of specific type
}

type ClusterHaResourcesIndexResponse []ClusterHaResourcesIndexResponseItem

type ClusterHaResourcesIndexResponseItem struct {
	Sid string `json:"sid,omitempty"` //
}

// List HA resources.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha/resources
func (c *Client) ClusterHaResourcesIndex(ctx context.Context, request *ClusterHaResourcesIndexRequest) (*ClusterHaResourcesIndexResponse, error) {

	method := "GET"
	path := "/cluster/ha/resources"

	var response ClusterHaResourcesIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
