// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesHostsWriteEtcHostsRequest struct {
	Data   string  `json:"data,omitempty"`   // The target content of /etc/hosts.
	Digest *string `json:"digest,omitempty"` // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Node   string  `json:"node,omitempty"`   // The cluster node name.
}

type NodesHostsWriteEtcHostsResponse struct{}

// Write /etc/hosts.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/hosts
func (c *Client) NodesHostsWriteEtcHosts(ctx context.Context, request *NodesHostsWriteEtcHostsRequest) (*NodesHostsWriteEtcHostsResponse, error) {

	method := "POST"
	path := "/nodes/{node}/hosts"

	var response NodesHostsWriteEtcHostsResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
