// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCertificatesCustomUploadCustomCertRequest struct {
	Certificates string  `json:"certificates,omitempty"` // PEM encoded certificate (chain).
	Force        *bool   `json:"force,omitempty"`        // Overwrite existing custom or ACME certificate files.
	Key          *string `json:"key,omitempty"`          // PEM encoded private key.
	Node         string  `json:"node,omitempty"`         // The cluster node name.
	Restart      *bool   `json:"restart,omitempty"`      // Restart pveproxy.
}

type NodesCertificatesCustomUploadCustomCertResponseSanItem string

type NodesCertificatesCustomUploadCustomCertResponse struct {
	Filename      *string                                                   `json:"filename,omitempty"`        //
	Fingerprint   *string                                                   `json:"fingerprint,omitempty"`     // Certificate SHA 256 fingerprint.
	Issuer        *string                                                   `json:"issuer,omitempty"`          // Certificate issuer name.
	Notafter      *int64                                                    `json:"notafter,omitempty"`        // Certificate's notAfter timestamp (UNIX epoch).
	Notbefore     *int64                                                    `json:"notbefore,omitempty"`       // Certificate's notBefore timestamp (UNIX epoch).
	Pem           *string                                                   `json:"pem,omitempty"`             // Certificate in PEM format
	PublicKeyBits *int64                                                    `json:"public-key-bits,omitempty"` // Certificate's public key size
	PublicKeyType *string                                                   `json:"public-key-type,omitempty"` // Certificate's public key algorithm
	San           *[]NodesCertificatesCustomUploadCustomCertResponseSanItem `json:"san,omitempty"`             // List of Certificate's SubjectAlternativeName entries.
	Subject       *string                                                   `json:"subject,omitempty"`         // Certificate subject name.
}

// Upload or update custom certificate chain and key.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/certificates/custom
func (c *Client) NodesCertificatesCustomUploadCustomCert(ctx context.Context, request *NodesCertificatesCustomUploadCustomCertRequest) (*NodesCertificatesCustomUploadCustomCertResponse, error) {

	method := "POST"
	path := "/nodes/{node}/certificates/custom"

	var response NodesCertificatesCustomUploadCustomCertResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
