// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephMonListmonRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesCephMonListmonResponse []NodesCephMonListmonResponseItem

type NodesCephMonListmonResponseItem struct {
	Addr *string `json:"addr,omitempty"` //
	Host *string `json:"host,omitempty"` //
	Name string  `json:"name,omitempty"` //
}

// Get Ceph monitor list.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/mon
func (c *Client) NodesCephMonListmon(ctx context.Context, request *NodesCephMonListmonRequest) (*NodesCephMonListmonResponse, error) {

	method := "GET"
	path := "/nodes/{node}/ceph/mon"

	var response NodesCephMonListmonResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
