// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuSnapshotConfigUpdateSnapshotConfigRequest struct {
	Description *string `json:"description,omitempty"` // A textual description or comment.
	Node        string  `json:"node,omitempty"`        // The cluster node name.
	Snapname    string  `json:"snapname,omitempty"`    // The name of the snapshot.
	Vmid        int64   `json:"vmid,omitempty"`        // The (unique) ID of the VM.
}

type NodesQemuSnapshotConfigUpdateSnapshotConfigResponse struct{}

// Update snapshot metadata.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/snapshot/{snapname}/config
func (c *Client) NodesQemuSnapshotConfigUpdateSnapshotConfig(ctx context.Context, request *NodesQemuSnapshotConfigUpdateSnapshotConfigRequest) (*NodesQemuSnapshotConfigUpdateSnapshotConfigResponse, error) {

	method := "PUT"
	path := "/nodes/{node}/qemu/{vmid}/snapshot/{snapname}/config"

	var response NodesQemuSnapshotConfigUpdateSnapshotConfigResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
