// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcStatusSuspendVmSuspendRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Vmid int64  `json:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesLxcStatusSuspendVmSuspendResponse string

// Suspend the container. This is experimental.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/status/suspend
func (c *Client) NodesLxcStatusSuspendVmSuspend(ctx context.Context, request *NodesLxcStatusSuspendVmSuspendRequest) (*NodesLxcStatusSuspendVmSuspendResponse, error) {

	method := "POST"
	path := "/nodes/{node}/lxc/{vmid}/status/suspend"

	var response NodesLxcStatusSuspendVmSuspendResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
