// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDnsDnsRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesDnsDnsResponse struct {
	Dns1   *string `json:"dns1,omitempty"`   // First name server IP address.
	Dns2   *string `json:"dns2,omitempty"`   // Second name server IP address.
	Dns3   *string `json:"dns3,omitempty"`   // Third name server IP address.
	Search *string `json:"search,omitempty"` // Search domain for host-name lookup.
}

// Read DNS settings.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/dns
func (c *Client) NodesDnsDns(ctx context.Context, request *NodesDnsDnsRequest) (*NodesDnsDnsResponse, error) {

	method := "GET"
	path := "/nodes/{node}/dns"

	var response NodesDnsDnsResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
