// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallAliasesCreateAliasRequest struct {
	Cidr    string  `json:"cidr,omitempty"`    // Network/IP specification in CIDR format.
	Comment *string `json:"comment,omitempty"` //
	Name    string  `json:"name,omitempty"`    // Alias name.
}

type ClusterFirewallAliasesCreateAliasResponse struct{}

// Create IP or Network Alias.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/aliases
func (c *Client) ClusterFirewallAliasesCreateAlias(ctx context.Context, request *ClusterFirewallAliasesCreateAliasRequest) (*ClusterFirewallAliasesCreateAliasResponse, error) {

	method := "POST"
	path := "/cluster/firewall/aliases"

	var response ClusterFirewallAliasesCreateAliasResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
