// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcSnapshotSnapshotCmdIdxRequest struct {
	Node     string `query:"node,omitempty"`     // The cluster node name.
	Snapname string `query:"snapname,omitempty"` // The name of the snapshot.
	Vmid     int64  `query:"vmid,omitempty"`     // The (unique) ID of the VM.
}

type NodesLxcSnapshotSnapshotCmdIdxResponseItem struct {
}

type NodesLxcSnapshotSnapshotCmdIdxResponse []NodesLxcSnapshotSnapshotCmdIdxResponseItem

// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/snapshot/{snapname}
func (c *Client) NodesLxcSnapshotSnapshotCmdIdx(ctx context.Context, request *NodesLxcSnapshotSnapshotCmdIdxRequest) (*NodesLxcSnapshotSnapshotCmdIdxResponse, error) {

	method := "GET"
	path := "/nodes/{node}/lxc/{vmid}/snapshot/{snapname}"

	var response NodesLxcSnapshotSnapshotCmdIdxResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
