// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcDestroyVmRequest struct {
	DestroyUnreferencedDisks *bool  `json:"destroy-unreferenced-disks,omitempty"` // If set, destroy additionally all disks with the VMID from all enabled storages which are not referenced in the config.
	Force                    *bool  `json:"force,omitempty"`                      // Force destroy, even if running.
	Node                     string `json:"node,omitempty"`                       // The cluster node name.
	Purge                    *bool  `json:"purge,omitempty"`                      // Remove container from all related configurations. For example, backup jobs, replication jobs or HA. Related ACLs and Firewall entries will *always* be removed.
	Vmid                     int64  `json:"vmid,omitempty"`                       // The (unique) ID of the VM.
}

type NodesLxcDestroyVmResponse string

// Destroy the container (also delete all uses files).
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}
func (c *Client) NodesLxcDestroyVm(ctx context.Context, request *NodesLxcDestroyVmRequest) (*NodesLxcDestroyVmResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/lxc/{vmid}"

	var response NodesLxcDestroyVmResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
