// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCertificatesAcmeCertificateRevokeCertificateRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
}

type NodesCertificatesAcmeCertificateRevokeCertificateResponse string

// Revoke existing certificate from CA.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/certificates/acme/certificate
func (c *Client) NodesCertificatesAcmeCertificateRevokeCertificate(ctx context.Context, request *NodesCertificatesAcmeCertificateRevokeCertificateRequest) (*NodesCertificatesAcmeCertificateRevokeCertificateResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/certificates/acme/certificate"

	var response NodesCertificatesAcmeCertificateRevokeCertificateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
