// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesScanLvmthinLvmthinscanRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vg   string `query:"vg,omitempty"`   //
}

type NodesScanLvmthinLvmthinscanResponseItem struct {
	Lv string `json:"lv,omitempty"` // The LVM Thin Pool name (LVM logical volume).
}

type NodesScanLvmthinLvmthinscanResponse []NodesScanLvmthinLvmthinscanResponseItem

// List local LVM Thin Pools.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/scan/lvmthin
func (c *Client) NodesScanLvmthinLvmthinscan(ctx context.Context, request *NodesScanLvmthinLvmthinscanRequest) (*NodesScanLvmthinLvmthinscanResponse, error) {

	method := "GET"
	path := "/nodes/{node}/scan/lvmthin"

	var response NodesScanLvmthinLvmthinscanResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
