// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuMtunnelMtunnelRequest struct {
	Bridges  *string `json:"bridges,omitempty"`  // List of network bridges to check availability. Will be checked again for actually used bridges during migration.
	Node     string  `json:"node,omitempty"`     // The cluster node name.
	Storages *string `json:"storages,omitempty"` // List of storages to check permission and availability. Will be checked again for all actually used storages during migration.
	Vmid     int64   `json:"vmid,omitempty"`     // The (unique) ID of the VM.
}

type NodesQemuMtunnelMtunnelResponse struct {
	Socket string `json:"socket,omitempty"` //
	Ticket string `json:"ticket,omitempty"` //
	Upid   string `json:"upid,omitempty"`   //
}

// Migration tunnel endpoint - only for internal use by VM migration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/mtunnel
func (c *Client) NodesQemuMtunnelMtunnel(ctx context.Context, request *NodesQemuMtunnelMtunnelRequest) (*NodesQemuMtunnelMtunnelResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/mtunnel"

	var response NodesQemuMtunnelMtunnelResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
