// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcStatusStartVmStartRequest struct {
	Debug    *bool  `json:"debug,omitempty"`    // If set, enables very verbose debug log-level on start.
	Node     string `json:"node,omitempty"`     // The cluster node name.
	Skiplock *bool  `json:"skiplock,omitempty"` // Ignore locks - only root is allowed to use this option.
	Vmid     int64  `json:"vmid,omitempty"`     // The (unique) ID of the VM.
}

type NodesLxcStatusStartVmStartResponse string

// Start the container.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/status/start
func (c *Client) NodesLxcStatusStartVmStart(ctx context.Context, request *NodesLxcStatusStartVmStartRequest) (*NodesLxcStatusStartVmStartResponse, error) {

	method := "POST"
	path := "/nodes/{node}/lxc/{vmid}/status/start"

	var response NodesLxcStatusStartVmStartResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
