// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnVnetsDeleteRequest struct {
	Vnet string `json:"vnet,omitempty"` // The SDN vnet object identifier.
}

type ClusterSdnVnetsDeleteResponse struct{}

// Delete sdn vnet object configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/vnets/{vnet}
func (c *Client) ClusterSdnVnetsDelete(ctx context.Context, request *ClusterSdnVnetsDeleteRequest) (*ClusterSdnVnetsDeleteResponse, error) {

	method := "DELETE"
	path := "/cluster/sdn/vnets/{vnet}"

	var response ClusterSdnVnetsDeleteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
