// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDisksInitgptInitgptRequest struct {
	Disk string  `json:"disk,omitempty"` // Block device name
	Node string  `json:"node,omitempty"` // The cluster node name.
	Uuid *string `json:"uuid,omitempty"` // UUID for the GPT table
}

type NodesDisksInitgptInitgptResponse string

// Initialize Disk with GPT
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/disks/initgpt
func (c *Client) NodesDisksInitgptInitgpt(ctx context.Context, request *NodesDisksInitgptInitgptRequest) (*NodesDisksInitgptInitgptResponse, error) {

	method := "POST"
	path := "/nodes/{node}/disks/initgpt"

	var response NodesDisksInitgptInitgptResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
