// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterCephFlagsGetFlagRequest struct {
	Flag string `query:"flag,omitempty"` // The name of the flag name to get.
}

type ClusterCephFlagsGetFlagResponse bool

// Get the status of a specific ceph flag.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ceph/flags/{flag}
func (c *Client) ClusterCephFlagsGetFlag(ctx context.Context, request *ClusterCephFlagsGetFlagRequest) (*ClusterCephFlagsGetFlagResponse, error) {

	method := "GET"
	path := "/cluster/ceph/flags/{flag}"

	var response ClusterCephFlagsGetFlagResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
