// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesScanLvmLvmscanRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesScanLvmLvmscanResponseItem struct {
	Vg string `json:"vg,omitempty"` // The LVM logical volume group name.
}

type NodesScanLvmLvmscanResponse []NodesScanLvmLvmscanResponseItem

// List local LVM volume groups.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/scan/lvm
func (c *Client) NodesScanLvmLvmscan(ctx context.Context, request *NodesScanLvmLvmscanRequest) (*NodesScanLvmLvmscanResponse, error) {

	method := "GET"
	path := "/nodes/{node}/scan/lvm"

	var response NodesScanLvmLvmscanResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
