// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessRolesDeleteRoleRequest struct {
	Roleid string `json:"roleid,omitempty"` //
}

type AccessRolesDeleteRoleResponse struct{}

// Delete role.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/roles/{roleid}
func (c *Client) AccessRolesDeleteRole(ctx context.Context, request *AccessRolesDeleteRoleRequest) (*AccessRolesDeleteRoleResponse, error) {

	method := "DELETE"
	path := "/access/roles/{roleid}"

	var response AccessRolesDeleteRoleResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
