// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterAcmeIndexRequest interface{}

type ClusterAcmeIndexResponse []ClusterAcmeIndexResponseItem

type ClusterAcmeIndexResponseItem struct {
}

// ACMEAccount index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/acme
func (c *Client) ClusterAcmeIndex(ctx context.Context, request *ClusterAcmeIndexRequest) (*ClusterAcmeIndexResponse, error) {

	method := "GET"
	path := "/cluster/acme"

	var response ClusterAcmeIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
