// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallGroupsGetRulesRequest struct {
	Group string `query:"group,omitempty"` // Security Group name.
}

type ClusterFirewallGroupsGetRulesResponse []ClusterFirewallGroupsGetRulesResponseItem

type ClusterFirewallGroupsGetRulesResponseItem struct {
	Pos int64 `json:"pos,omitempty"` //
}

// List rules.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/groups/{group}
func (c *Client) ClusterFirewallGroupsGetRules(ctx context.Context, request *ClusterFirewallGroupsGetRulesRequest) (*ClusterFirewallGroupsGetRulesResponse, error) {

	method := "GET"
	path := "/cluster/firewall/groups/{group}"

	var response ClusterFirewallGroupsGetRulesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
