// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuFirewallAliasesCreateAliasRequest struct {
	Cidr    string  `json:"cidr,omitempty"`    // Network/IP specification in CIDR format.
	Comment *string `json:"comment,omitempty"` //
	Name    string  `json:"name,omitempty"`    // Alias name.
	Node    string  `json:"node,omitempty"`    // The cluster node name.
	Vmid    int64   `json:"vmid,omitempty"`    // The (unique) ID of the VM.
}

type NodesQemuFirewallAliasesCreateAliasResponse struct{}

// Create IP or Network Alias.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/firewall/aliases
func (c *Client) NodesQemuFirewallAliasesCreateAlias(ctx context.Context, request *NodesQemuFirewallAliasesCreateAliasRequest) (*NodesQemuFirewallAliasesCreateAliasResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/firewall/aliases"

	var response NodesQemuFirewallAliasesCreateAliasResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
