// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesReplicationIndexRequest struct {
	Id   string `query:"id,omitempty"`   // Replication Job ID. The ID is composed of a Guest ID and a job number, separated by a hyphen, i.e. '<GUEST>-<JOBNUM>'.
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesReplicationIndexResponse []NodesReplicationIndexResponseItem

type NodesReplicationIndexResponseItem struct {
}

// Directory index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/replication/{id}
func (c *Client) NodesReplicationIndex(ctx context.Context, request *NodesReplicationIndexRequest) (*NodesReplicationIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/replication/{id}"

	var response NodesReplicationIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
