// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterHaGroupsReadRequest struct {
	Group string `query:"group,omitempty"` // The HA group identifier.
}

type ClusterHaGroupsReadResponse interface{}

// Read ha group configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha/groups/{group}
func (c *Client) ClusterHaGroupsRead(ctx context.Context, request *ClusterHaGroupsReadRequest) (*ClusterHaGroupsReadResponse, error) {

	method := "GET"
	path := "/cluster/ha/groups/{group}"

	var response ClusterHaGroupsReadResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
