// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuVncwebsocketVncwebsocketRequest struct {
	Node      string `query:"node,omitempty"`      // The cluster node name.
	Port      int64  `query:"port,omitempty"`      // Port number returned by previous vncproxy call.
	Vmid      int64  `query:"vmid,omitempty"`      // The (unique) ID of the VM.
	Vncticket string `query:"vncticket,omitempty"` // Ticket from previous call to vncproxy.
}

type NodesQemuVncwebsocketVncwebsocketResponse struct {
	Port string `json:"port,omitempty"` //
}

// Opens a weksocket for VNC traffic.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/vncwebsocket
func (c *Client) NodesQemuVncwebsocketVncwebsocket(ctx context.Context, request *NodesQemuVncwebsocketVncwebsocketRequest) (*NodesQemuVncwebsocketVncwebsocketResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/vncwebsocket"

	var response NodesQemuVncwebsocketVncwebsocketResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
