// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesAptUpdateListUpdatesRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesAptUpdateListUpdatesResponse []NodesAptUpdateListUpdatesResponseItem

type NodesAptUpdateListUpdatesResponseItem struct {
}

// List available updates.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/apt/update
func (c *Client) NodesAptUpdateListUpdates(ctx context.Context, request *NodesAptUpdateListUpdatesRequest) (*NodesAptUpdateListUpdatesResponse, error) {

	method := "GET"
	path := "/nodes/{node}/apt/update"

	var response NodesAptUpdateListUpdatesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
