// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcSnapshotDelsnapshotRequest struct {
	Force    *bool  `json:"force,omitempty"`    // For removal from config file, even if removing disk snapshots fails.
	Node     string `json:"node,omitempty"`     // The cluster node name.
	Snapname string `json:"snapname,omitempty"` // The name of the snapshot.
	Vmid     int64  `json:"vmid,omitempty"`     // The (unique) ID of the VM.
}

// the task ID.
type NodesLxcSnapshotDelsnapshotResponse string

// Delete a LXC snapshot.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/snapshot/{snapname}
func (c *Client) NodesLxcSnapshotDelsnapshot(ctx context.Context, request *NodesLxcSnapshotDelsnapshotRequest) (*NodesLxcSnapshotDelsnapshotResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/lxc/{vmid}/snapshot/{snapname}"

	var response NodesLxcSnapshotDelsnapshotResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
