// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallOptionsSetOptionsRequest struct {
	Delete       *string `json:"delete,omitempty"`        // A list of settings you want to delete.
	Digest       *string `json:"digest,omitempty"`        // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Ebtables     *bool   `json:"ebtables,omitempty"`      // Enable ebtables rules cluster wide.
	Enable       *int64  `json:"enable,omitempty"`        // Enable or disable the firewall cluster wide.
	LogRatelimit *string `json:"log_ratelimit,omitempty"` // Log ratelimiting settings
	PolicyIn     *string `json:"policy_in,omitempty"`     // Input policy.
	PolicyOut    *string `json:"policy_out,omitempty"`    // Output policy.
}

type ClusterFirewallOptionsSetOptionsResponse struct{}

// Set Firewall options.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/options
func (c *Client) ClusterFirewallOptionsSetOptions(ctx context.Context, request *ClusterFirewallOptionsSetOptionsRequest) (*ClusterFirewallOptionsSetOptionsResponse, error) {

	method := "PUT"
	path := "/cluster/firewall/options"

	var response ClusterFirewallOptionsSetOptionsResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
