// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentFsfreezeFreezeFsfreezeFreezeRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Vmid int64  `json:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentFsfreezeFreezeFsfreezeFreezeResponse interface{}

// Execute fsfreeze-freeze.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/fsfreeze-freeze
func (c *Client) NodesQemuAgentFsfreezeFreezeFsfreezeFreeze(ctx context.Context, request *NodesQemuAgentFsfreezeFreezeFsfreezeFreezeRequest) (*NodesQemuAgentFsfreezeFreezeFsfreezeFreezeResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent/fsfreeze-freeze"

	var response NodesQemuAgentFsfreezeFreezeFsfreezeFreezeResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
