// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesMigrateallMigrateallRequest struct {
	Maxworkers     *int64  `json:"maxworkers,omitempty"`       // Maximal number of parallel migration job. If not set use 'max_workers' from datacenter.cfg, one of both must be set!
	Node           string  `json:"node,omitempty"`             // The cluster node name.
	Target         string  `json:"target,omitempty"`           // Target node.
	Vms            *string `json:"vms,omitempty"`              // Only consider Guests with these IDs.
	WithLocalDisks *bool   `json:"with-local-disks,omitempty"` // Enable live storage migration for local disk
}

type NodesMigrateallMigrateallResponse string

// Migrate all VMs and Containers.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/migrateall
func (c *Client) NodesMigrateallMigrateall(ctx context.Context, request *NodesMigrateallMigrateallRequest) (*NodesMigrateallMigrateallResponse, error) {

	method := "POST"
	path := "/nodes/{node}/migrateall"

	var response NodesMigrateallMigrateallResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
