// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessUsersTokenRemoveTokenRequest struct {
	Tokenid string `json:"tokenid,omitempty"` // User-specific token identifier.
	Userid  string `json:"userid,omitempty"`  // User ID
}

type AccessUsersTokenRemoveTokenResponse struct{}

// Remove API token for a specific user.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/users/{userid}/token/{tokenid}
func (c *Client) AccessUsersTokenRemoveToken(ctx context.Context, request *AccessUsersTokenRemoveTokenRequest) (*AccessUsersTokenRemoveTokenResponse, error) {

	method := "DELETE"
	path := "/access/users/{userid}/token/{tokenid}"

	var response AccessUsersTokenRemoveTokenResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
