// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterMetricsServerReadRequest struct {
	Id string `query:"id,omitempty"` //
}

type ClusterMetricsServerReadResponse interface{}

// Read metric server configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/metrics/server/{id}
func (c *Client) ClusterMetricsServerRead(ctx context.Context, request *ClusterMetricsServerReadRequest) (*ClusterMetricsServerReadResponse, error) {

	method := "GET"
	path := "/cluster/metrics/server/{id}"

	var response ClusterMetricsServerReadResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
