// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesStopallStopallRequest struct {
	Node string  `json:"node,omitempty"` // The cluster node name.
	Vms  *string `json:"vms,omitempty"`  // Only consider Guests with these IDs.
}

type NodesStopallStopallResponse string

// Stop all VMs and Containers.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/stopall
func (c *Client) NodesStopallStopall(ctx context.Context, request *NodesStopallStopallRequest) (*NodesStopallStopallResponse, error) {

	method := "POST"
	path := "/nodes/{node}/stopall"

	var response NodesStopallStopallResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
