// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephOsdScrubScrubRequest struct {
	Deep  *bool  `json:"deep,omitempty"`  // If set, instructs a deep scrub instead of a normal one.
	Node  string `json:"node,omitempty"`  // The cluster node name.
	Osdid int64  `json:"osdid,omitempty"` // OSD ID
}

type NodesCephOsdScrubScrubResponse struct{}

// Instruct the OSD to scrub.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/osd/{osdid}/scrub
func (c *Client) NodesCephOsdScrubScrub(ctx context.Context, request *NodesCephOsdScrubScrubRequest) (*NodesCephOsdScrubScrubResponse, error) {

	method := "POST"
	path := "/nodes/{node}/ceph/osd/{osdid}/scrub"

	var response NodesCephOsdScrubScrubResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
