// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesScanIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesScanIndexResponseItem struct {
	Method string `json:"method,omitempty"` //
}

type NodesScanIndexResponse []NodesScanIndexResponseItem

// Index of available scan methods
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/scan
func (c *Client) NodesScanIndex(ctx context.Context, request *NodesScanIndexRequest) (*NodesScanIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/scan"

	var response NodesScanIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
