// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuFirewallAliasesReadAliasRequest struct {
	Name string `query:"name,omitempty"` // Alias name.
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesQemuFirewallAliasesReadAliasResponse interface{}

// Read alias.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/firewall/aliases/{name}
func (c *Client) NodesQemuFirewallAliasesReadAlias(ctx context.Context, request *NodesQemuFirewallAliasesReadAliasRequest) (*NodesQemuFirewallAliasesReadAliasResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/firewall/aliases/{name}"

	var response NodesQemuFirewallAliasesReadAliasResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
