// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnControllersCreateRequest struct {
	Asn                     *int64  `json:"asn,omitempty"`                         // autonomous system number
	BgpMultipathAsPathRelax *bool   `json:"bgp-multipath-as-path-relax,omitempty"` //
	Controller              string  `json:"controller,omitempty"`                  // The SDN controller object identifier.
	Ebgp                    *bool   `json:"ebgp,omitempty"`                        // Enable ebgp. (remote-as external)
	EbgpMultihop            *int64  `json:"ebgp-multihop,omitempty"`               //
	Loopback                *string `json:"loopback,omitempty"`                    // source loopback interface.
	Node                    *string `json:"node,omitempty"`                        // The cluster node name.
	Peers                   *string `json:"peers,omitempty"`                       // peers address list.
	Type                    string  `json:"type,omitempty"`                        // Plugin type.
}

type ClusterSdnControllersCreateResponse struct{}

// Create a new sdn controller object.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/controllers
func (c *Client) ClusterSdnControllersCreate(ctx context.Context, request *ClusterSdnControllersCreateRequest) (*ClusterSdnControllersCreateResponse, error) {

	method := "POST"
	path := "/cluster/sdn/controllers"

	var response ClusterSdnControllersCreateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
