// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentGetOsinfoGetOsinfoRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentGetOsinfoGetOsinfoResponse interface{}

// Execute get-osinfo.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/get-osinfo
func (c *Client) NodesQemuAgentGetOsinfoGetOsinfo(ctx context.Context, request *NodesQemuAgentGetOsinfoGetOsinfoRequest) (*NodesQemuAgentGetOsinfoGetOsinfoResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/agent/get-osinfo"

	var response NodesQemuAgentGetOsinfoGetOsinfoResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
