// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesScanIscsiIscsiscanRequest struct {
	Node   string `query:"node,omitempty"`   // The cluster node name.
	Portal string `query:"portal,omitempty"` // The iSCSI portal (IP or DNS name with optional port).
}

type NodesScanIscsiIscsiscanResponse []NodesScanIscsiIscsiscanResponseItem

type NodesScanIscsiIscsiscanResponseItem struct {
	Portal string `json:"portal,omitempty"` // The iSCSI portal name.
	Target string `json:"target,omitempty"` // The iSCSI target name.
}

// Scan remote iSCSI server.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/scan/iscsi
func (c *Client) NodesScanIscsiIscsiscan(ctx context.Context, request *NodesScanIscsiIscsiscanRequest) (*NodesScanIscsiIscsiscanResponse, error) {

	method := "GET"
	path := "/nodes/{node}/scan/iscsi"

	var response NodesScanIscsiIscsiscanResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
