// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephConfigConfigRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesCephConfigConfigResponse string

// Get Ceph configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/config
func (c *Client) NodesCephConfigConfig(ctx context.Context, request *NodesCephConfigConfigRequest) (*NodesCephConfigConfigResponse, error) {

	method := "GET"
	path := "/nodes/{node}/ceph/config"

	var response NodesCephConfigConfigResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
