// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuVncproxyVncproxyRequest struct {
	GeneratePassword *bool  `json:"generate-password,omitempty"` // Generates a random password to be used as ticket instead of the API ticket.
	Node             string `json:"node,omitempty"`              // The cluster node name.
	Vmid             int64  `json:"vmid,omitempty"`              // The (unique) ID of the VM.
	Websocket        *bool  `json:"websocket,omitempty"`         // starts websockify instead of vncproxy
}

type NodesQemuVncproxyVncproxyResponse struct {
	Cert     string  `json:"cert,omitempty"`     //
	Password *string `json:"password,omitempty"` // Returned if requested with 'generate-password' param. Consists of printable ASCII characters ('!' .. '~').
	Port     int64   `json:"port,omitempty"`     //
	Ticket   string  `json:"ticket,omitempty"`   //
	Upid     string  `json:"upid,omitempty"`     //
	User     string  `json:"user,omitempty"`     //
}

// Creates a TCP VNC proxy connections.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/vncproxy
func (c *Client) NodesQemuVncproxyVncproxy(ctx context.Context, request *NodesQemuVncproxyVncproxyRequest) (*NodesQemuVncproxyVncproxyResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/vncproxy"

	var response NodesQemuVncproxyVncproxyResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
