// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentSuspendDiskSuspendDiskRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Vmid int64  `json:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentSuspendDiskSuspendDiskResponse interface{}

// Execute suspend-disk.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/suspend-disk
func (c *Client) NodesQemuAgentSuspendDiskSuspendDisk(ctx context.Context, request *NodesQemuAgentSuspendDiskSuspendDiskRequest) (*NodesQemuAgentSuspendDiskSuspendDiskResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent/suspend-disk"

	var response NodesQemuAgentSuspendDiskSuspendDiskResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
