// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type StorageDeleteRequest struct {
	Storage string `json:"storage,omitempty"` // The storage identifier.
}

type StorageDeleteResponse struct{}

// Delete storage configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/storage/{storage}
func (c *Client) StorageDelete(ctx context.Context, request *StorageDeleteRequest) (*StorageDeleteResponse, error) {

	method := "DELETE"
	path := "/storage/{storage}"

	var response StorageDeleteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
