// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcFirewallIpsetGetIpsetRequest struct {
	Name string `query:"name,omitempty"` // IP set name.
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesLxcFirewallIpsetGetIpsetResponse []NodesLxcFirewallIpsetGetIpsetResponseItem

type NodesLxcFirewallIpsetGetIpsetResponseItem struct {
	Cidr    string  `json:"cidr,omitempty"`    //
	Comment *string `json:"comment,omitempty"` //
	Digest  string  `json:"digest,omitempty"`  // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Nomatch *bool   `json:"nomatch,omitempty"` //
}

// List IPSet content
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/firewall/ipset/{name}
func (c *Client) NodesLxcFirewallIpsetGetIpset(ctx context.Context, request *NodesLxcFirewallIpsetGetIpsetRequest) (*NodesLxcFirewallIpsetGetIpsetResponse, error) {

	method := "GET"
	path := "/nodes/{node}/lxc/{vmid}/firewall/ipset/{name}"

	var response NodesLxcFirewallIpsetGetIpsetResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
