// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentGetTimezoneGetTimezoneRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentGetTimezoneGetTimezoneResponse interface{}

// Execute get-timezone.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/get-timezone
func (c *Client) NodesQemuAgentGetTimezoneGetTimezone(ctx context.Context, request *NodesQemuAgentGetTimezoneGetTimezoneRequest) (*NodesQemuAgentGetTimezoneGetTimezoneResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/agent/get-timezone"

	var response NodesQemuAgentGetTimezoneGetTimezoneResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
