// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterHaGroupsCreateRequest struct {
	Comment    *string `json:"comment,omitempty"`    // Description.
	Group      string  `json:"group,omitempty"`      // The HA group identifier.
	Nodes      string  `json:"nodes,omitempty"`      // List of cluster node names with optional priority.
	Nofailback *bool   `json:"nofailback,omitempty"` // The CRM tries to run services on the node with the highest priority. If a node with higher priority comes online, the CRM migrates the service to that node. Enabling nofailback prevents that behavior.
	Restricted *bool   `json:"restricted,omitempty"` // Resources bound to restricted groups may only run on nodes defined by the group.
	Type       *string `json:"type,omitempty"`       // Group type.
}

type ClusterHaGroupsCreateResponse struct{}

// Create a new HA group.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha/groups
func (c *Client) ClusterHaGroupsCreate(ctx context.Context, request *ClusterHaGroupsCreateRequest) (*ClusterHaGroupsCreateResponse, error) {

	method := "POST"
	path := "/cluster/ha/groups"

	var response ClusterHaGroupsCreateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
