// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnDnsIndexRequest struct {
	Type *string `query:"type,omitempty"` // Only list sdn dns of specific type
}

type ClusterSdnDnsIndexResponse []ClusterSdnDnsIndexResponseItem

type ClusterSdnDnsIndexResponseItem struct {
	Dns  string `json:"dns,omitempty"`  //
	Type string `json:"type,omitempty"` //
}

// SDN dns index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/dns
func (c *Client) ClusterSdnDnsIndex(ctx context.Context, request *ClusterSdnDnsIndexRequest) (*ClusterSdnDnsIndexResponse, error) {

	method := "GET"
	path := "/cluster/sdn/dns"

	var response ClusterSdnDnsIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
