// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentFsfreezeThawFsfreezeThawRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Vmid int64  `json:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentFsfreezeThawFsfreezeThawResponse interface{}

// Execute fsfreeze-thaw.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/fsfreeze-thaw
func (c *Client) NodesQemuAgentFsfreezeThawFsfreezeThaw(ctx context.Context, request *NodesQemuAgentFsfreezeThawFsfreezeThawRequest) (*NodesQemuAgentFsfreezeThawFsfreezeThawResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent/fsfreeze-thaw"

	var response NodesQemuAgentFsfreezeThawFsfreezeThawResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
