// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesSdnZonesIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesSdnZonesIndexResponseItem struct {
	Status string `json:"status,omitempty"` // Status of zone
	Zone   string `json:"zone,omitempty"`   // The SDN zone object identifier.
}

type NodesSdnZonesIndexResponse []NodesSdnZonesIndexResponseItem

// Get status for all zones.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/sdn/zones
func (c *Client) NodesSdnZonesIndex(ctx context.Context, request *NodesSdnZonesIndexRequest) (*NodesSdnZonesIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/sdn/zones"

	var response NodesSdnZonesIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
