// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type PoolsIndexRequest interface{}

type PoolsIndexResponseItem struct {
	Poolid string `json:"poolid,omitempty"` //
}

type PoolsIndexResponse []PoolsIndexResponseItem

// Pool index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/pools
func (c *Client) PoolsIndex(ctx context.Context, request *PoolsIndexRequest) (*PoolsIndexResponse, error) {

	method := "GET"
	path := "/pools"

	var response PoolsIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
