// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentPingPingRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Vmid int64  `json:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentPingPingResponse interface{}

// Execute ping.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/ping
func (c *Client) NodesQemuAgentPingPing(ctx context.Context, request *NodesQemuAgentPingPingRequest) (*NodesQemuAgentPingPingResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent/ping"

	var response NodesQemuAgentPingPingResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
