// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallRulesGetRuleRequest struct {
	Pos *int64 `query:"pos,omitempty"` // Update rule at position <pos>.
}

type ClusterFirewallRulesGetRuleResponse struct {
	Action    string  `json:"action,omitempty"`    //
	Comment   *string `json:"comment,omitempty"`   //
	Dest      *string `json:"dest,omitempty"`      //
	Dport     *string `json:"dport,omitempty"`     //
	Enable    *int64  `json:"enable,omitempty"`    //
	IcmpType  *string `json:"icmp-type,omitempty"` //
	Iface     *string `json:"iface,omitempty"`     //
	Ipversion *int64  `json:"ipversion,omitempty"` //
	Log       *string `json:"log,omitempty"`       // Log level for firewall rule
	Macro     *string `json:"macro,omitempty"`     //
	Pos       int64   `json:"pos,omitempty"`       //
	Proto     *string `json:"proto,omitempty"`     //
	Source    *string `json:"source,omitempty"`    //
	Sport     *string `json:"sport,omitempty"`     //
	Type      string  `json:"type,omitempty"`      //
}

// Get single rule data.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall/rules/{pos}
func (c *Client) ClusterFirewallRulesGetRule(ctx context.Context, request *ClusterFirewallRulesGetRuleRequest) (*ClusterFirewallRulesGetRuleResponse, error) {

	method := "GET"
	path := "/cluster/firewall/rules/{pos}"

	var response ClusterFirewallRulesGetRuleResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
