// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterCephMetadataMetadataRequest struct {
	Scope *string `query:"scope,omitempty"` //
}

type ClusterCephMetadataMetadataResponse interface{}

// Get ceph metadata.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ceph/metadata
func (c *Client) ClusterCephMetadataMetadata(ctx context.Context, request *ClusterCephMetadataMetadataRequest) (*ClusterCephMetadataMetadataResponse, error) {

	method := "GET"
	path := "/cluster/ceph/metadata"

	var response ClusterCephMetadataMetadataResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
