// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesStorageContentCopyRequest struct {
	Node       string  `json:"node,omitempty"`        // The cluster node name.
	Storage    *string `json:"storage,omitempty"`     // The storage identifier.
	Target     string  `json:"target,omitempty"`      // Target volume identifier
	TargetNode *string `json:"target_node,omitempty"` // Target node. Default is local node.
	Volume     string  `json:"volume,omitempty"`      // Source volume identifier
}

type NodesStorageContentCopyResponse string

// Copy a volume. This is experimental code - do not use.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/storage/{storage}/content/{volume}
func (c *Client) NodesStorageContentCopy(ctx context.Context, request *NodesStorageContentCopyRequest) (*NodesStorageContentCopyResponse, error) {

	method := "POST"
	path := "/nodes/{node}/storage/{storage}/content/{volume}"

	var response NodesStorageContentCopyResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
