// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessUsersTfaReadUserTfaTypeRequest struct {
	Multiple *bool  `query:"multiple,omitempty"` // Request all entries as an array.
	Userid   string `query:"userid,omitempty"`   // User ID
}

// A TFA type.
type AccessUsersTfaReadUserTfaTypeResponseTypesItem string

type AccessUsersTfaReadUserTfaTypeResponse struct {
	Realm *string                                           `json:"realm,omitempty"` // The type of TFA the users realm has set, if any.
	Types *[]AccessUsersTfaReadUserTfaTypeResponseTypesItem `json:"types,omitempty"` // Array of the user configured TFA types, if any. Only available if 'multiple' was not passed.
	User  *string                                           `json:"user,omitempty"`  // The type of TFA the user has set, if any. Only set if 'multiple' was not passed.
}

// Get user TFA types (Personal and Realm).
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/users/{userid}/tfa
func (c *Client) AccessUsersTfaReadUserTfaType(ctx context.Context, request *AccessUsersTfaReadUserTfaTypeRequest) (*AccessUsersTfaReadUserTfaTypeResponse, error) {

	method := "GET"
	path := "/access/users/{userid}/tfa"

	var response AccessUsersTfaReadUserTfaTypeResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
