// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephCmdSafetyCmdSafetyRequest struct {
	Action  string `query:"action,omitempty"`  // Action to check
	Id      string `query:"id,omitempty"`      // ID of the service
	Node    string `query:"node,omitempty"`    // The cluster node name.
	Service string `query:"service,omitempty"` // Service type
}

type NodesCephCmdSafetyCmdSafetyResponse struct {
	Safe   bool    `json:"safe,omitempty"`   // If it is safe to run the command.
	Status *string `json:"status,omitempty"` // Status message given by Ceph.
}

// Heuristical check if it is safe to perform an action.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/cmd-safety
func (c *Client) NodesCephCmdSafetyCmdSafety(ctx context.Context, request *NodesCephCmdSafetyCmdSafetyRequest) (*NodesCephCmdSafetyCmdSafetyResponse, error) {

	method := "GET"
	path := "/nodes/{node}/ceph/cmd-safety"

	var response NodesCephCmdSafetyCmdSafetyResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
