// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesScanZfsZfsscanRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesScanZfsZfsscanResponseItem struct {
	Pool string `json:"pool,omitempty"` // ZFS pool name.
}

type NodesScanZfsZfsscanResponse []NodesScanZfsZfsscanResponseItem

// Scan zfs pool list on local node.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/scan/zfs
func (c *Client) NodesScanZfsZfsscan(ctx context.Context, request *NodesScanZfsZfsscanRequest) (*NodesScanZfsZfsscanResponse, error) {

	method := "GET"
	path := "/nodes/{node}/scan/zfs"

	var response NodesScanZfsZfsscanResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
