// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentFstrimFstrimRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
	Vmid int64  `json:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a single `result` property.
type NodesQemuAgentFstrimFstrimResponse interface{}

// Execute fstrim.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/fstrim
func (c *Client) NodesQemuAgentFstrimFstrim(ctx context.Context, request *NodesQemuAgentFstrimFstrimRequest) (*NodesQemuAgentFstrimFstrimResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/agent/fstrim"

	var response NodesQemuAgentFstrimFstrimResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
