// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephOsdCreateosdRequest struct {
	CrushDeviceClass *string  `json:"crush-device-class,omitempty"` // Set the device class of the OSD in crush.
	DbDev            *string  `json:"db_dev,omitempty"`             // Block device name for block.db.
	DbDevSize        *float64 `json:"db_dev_size,omitempty"`        // Size in GiB for block.db.
	Dev              string   `json:"dev,omitempty"`                // Block device name.
	Encrypted        *bool    `json:"encrypted,omitempty"`          // Enables encryption of the OSD.
	Node             string   `json:"node,omitempty"`               // The cluster node name.
	WalDev           *string  `json:"wal_dev,omitempty"`            // Block device name for block.wal.
	WalDevSize       *float64 `json:"wal_dev_size,omitempty"`       // Size in GiB for block.wal.
}

type NodesCephOsdCreateosdResponse string

// Create OSD
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/osd
func (c *Client) NodesCephOsdCreateosd(ctx context.Context, request *NodesCephOsdCreateosdRequest) (*NodesCephOsdCreateosdResponse, error) {

	method := "POST"
	path := "/nodes/{node}/ceph/osd"

	var response NodesCephOsdCreateosdResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
