// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcResizeResizeVmRequest struct {
	Digest *string `json:"digest,omitempty"` // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Disk   string  `json:"disk,omitempty"`   // The disk you want to resize.
	Node   string  `json:"node,omitempty"`   // The cluster node name.
	Size   string  `json:"size,omitempty"`   // The new size. With the '+' sign the value is added to the actual size of the volume and without it, the value is taken as an absolute one. Shrinking disk size is not supported.
	Vmid   int64   `json:"vmid,omitempty"`   // The (unique) ID of the VM.
}

// the task ID.
type NodesLxcResizeResizeVmResponse string

// Resize a container mount point.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/resize
func (c *Client) NodesLxcResizeResizeVm(ctx context.Context, request *NodesLxcResizeResizeVmRequest) (*NodesLxcResizeResizeVmResponse, error) {

	method := "PUT"
	path := "/nodes/{node}/lxc/{vmid}/resize"

	var response NodesLxcResizeResizeVmResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
