// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCephFsIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesCephFsIndexResponseItem struct {
	DataPool     string `json:"data_pool,omitempty"`     // The name of the data pool.
	MetadataPool string `json:"metadata_pool,omitempty"` // The name of the metadata pool.
	Name         string `json:"name,omitempty"`          // The ceph filesystem name.
}

type NodesCephFsIndexResponse []NodesCephFsIndexResponseItem

// Directory index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/ceph/fs
func (c *Client) NodesCephFsIndex(ctx context.Context, request *NodesCephFsIndexRequest) (*NodesCephFsIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/ceph/fs"

	var response NodesCephFsIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
