// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type PoolsDeletePoolRequest struct {
	Poolid string `json:"poolid,omitempty"` //
}

type PoolsDeletePoolResponse struct{}

// Delete pool.
// https://pve.proxmox.com/pve-docs/api-viewer/#/pools/{poolid}
func (c *Client) PoolsDeletePool(ctx context.Context, request *PoolsDeletePoolRequest) (*PoolsDeletePoolResponse, error) {

	method := "DELETE"
	path := "/pools/{poolid}"

	var response PoolsDeletePoolResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
