// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterFirewallIndexRequest interface{}

type ClusterFirewallIndexResponse []ClusterFirewallIndexResponseItem

type ClusterFirewallIndexResponseItem struct {
}

// Directory index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/firewall
func (c *Client) ClusterFirewallIndex(ctx context.Context, request *ClusterFirewallIndexRequest) (*ClusterFirewallIndexResponse, error) {

	method := "GET"
	path := "/cluster/firewall"

	var response ClusterFirewallIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
