// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCertificatesAcmeCertificateRenewCertificateRequest struct {
	Force *bool  `json:"force,omitempty"` // Force renewal even if expiry is more than 30 days away.
	Node  string `json:"node,omitempty"`  // The cluster node name.
}

type NodesCertificatesAcmeCertificateRenewCertificateResponse string

// Renew existing certificate from CA.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/certificates/acme/certificate
func (c *Client) NodesCertificatesAcmeCertificateRenewCertificate(ctx context.Context, request *NodesCertificatesAcmeCertificateRenewCertificateRequest) (*NodesCertificatesAcmeCertificateRenewCertificateResponse, error) {

	method := "PUT"
	path := "/nodes/{node}/certificates/acme/certificate"

	var response NodesCertificatesAcmeCertificateRenewCertificateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
