// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesAplinfoAplDownloadRequest struct {
	Node     string `json:"node,omitempty"`     // The cluster node name.
	Storage  string `json:"storage,omitempty"`  // The storage where the template will be stored
	Template string `json:"template,omitempty"` // The template which will downloaded
}

type NodesAplinfoAplDownloadResponse string

// Download appliance templates.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/aplinfo
func (c *Client) NodesAplinfoAplDownload(ctx context.Context, request *NodesAplinfoAplDownloadRequest) (*NodesAplinfoAplDownloadResponse, error) {

	method := "POST"
	path := "/nodes/{node}/aplinfo"

	var response NodesAplinfoAplDownloadResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
