// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuAgentFileReadFileReadRequest struct {
	File string `query:"file,omitempty"` // The path to the file
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

// Returns an object with a `content` property.
type NodesQemuAgentFileReadFileReadResponse struct {
	Content   string `json:"content,omitempty"`   // The content of the file, maximum 16777216
	Truncated *bool  `json:"truncated,omitempty"` // If set to 1, the output is truncated and not complete
}

// Reads the given file via guest agent. Is limited to 16777216 bytes.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/agent/file-read
func (c *Client) NodesQemuAgentFileReadFileRead(ctx context.Context, request *NodesQemuAgentFileReadFileReadRequest) (*NodesQemuAgentFileReadFileReadResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/agent/file-read"

	var response NodesQemuAgentFileReadFileReadResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
