// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCertificatesIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesCertificatesIndexResponse []NodesCertificatesIndexResponseItem

type NodesCertificatesIndexResponseItem struct {
}

// Node index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/certificates
func (c *Client) NodesCertificatesIndex(ctx context.Context, request *NodesCertificatesIndexRequest) (*NodesCertificatesIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/certificates"

	var response NodesCertificatesIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
