// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterIndexRequest interface{}

type ClusterIndexResponse []ClusterIndexResponseItem

type ClusterIndexResponseItem struct {
}

// Cluster index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster
func (c *Client) ClusterIndex(ctx context.Context, request *ClusterIndexRequest) (*ClusterIndexResponse, error) {

	method := "GET"
	path := "/cluster"

	var response ClusterIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
