// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuFirewallIpsetIpsetIndexRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
	Vmid int64  `query:"vmid,omitempty"` // The (unique) ID of the VM.
}

type NodesQemuFirewallIpsetIpsetIndexResponse []NodesQemuFirewallIpsetIpsetIndexResponseItem

type NodesQemuFirewallIpsetIpsetIndexResponseItem struct {
	Comment *string `json:"comment,omitempty"` //
	Digest  string  `json:"digest,omitempty"`  // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Name    string  `json:"name,omitempty"`    // IP set name.
}

// List IPSets
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/firewall/ipset
func (c *Client) NodesQemuFirewallIpsetIpsetIndex(ctx context.Context, request *NodesQemuFirewallIpsetIpsetIndexRequest) (*NodesQemuFirewallIpsetIpsetIndexResponse, error) {

	method := "GET"
	path := "/nodes/{node}/qemu/{vmid}/firewall/ipset"

	var response NodesQemuFirewallIpsetIpsetIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
