// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcFirewallIpsetCreateIpsetRequest struct {
	Comment *string `json:"comment,omitempty"` //
	Digest  *string `json:"digest,omitempty"`  // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Name    string  `json:"name,omitempty"`    // IP set name.
	Node    string  `json:"node,omitempty"`    // The cluster node name.
	Rename  *string `json:"rename,omitempty"`  // Rename an existing IPSet. You can set 'rename' to the same value as 'name' to update the 'comment' of an existing IPSet.
	Vmid    int64   `json:"vmid,omitempty"`    // The (unique) ID of the VM.
}

type NodesLxcFirewallIpsetCreateIpsetResponse struct{}

// Create new IPSet
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/firewall/ipset
func (c *Client) NodesLxcFirewallIpsetCreateIpset(ctx context.Context, request *NodesLxcFirewallIpsetCreateIpsetRequest) (*NodesLxcFirewallIpsetCreateIpsetResponse, error) {

	method := "POST"
	path := "/nodes/{node}/lxc/{vmid}/firewall/ipset"

	var response NodesLxcFirewallIpsetCreateIpsetResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
