// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessTfaListUserTfaRequest struct {
	Userid string `query:"userid,omitempty"` // User ID
}

// A list of the user's TFA entries.
type AccessTfaListUserTfaResponse []AccessTfaListUserTfaResponseItem

// TFA Entry.
type AccessTfaListUserTfaResponseItem struct {
	Created     int64  `json:"created,omitempty"`     // Creation time of this entry as unix epoch.
	Description string `json:"description,omitempty"` // User chosen description for this entry.
	Enable      *bool  `json:"enable,omitempty"`      // Whether this TFA entry is currently enabled.
	Id          string `json:"id,omitempty"`          // The id used to reference this entry.
	Type        string `json:"type,omitempty"`        // TFA Entry Type.
}

// List TFA configurations of users.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/tfa/{userid}
func (c *Client) AccessTfaListUserTfa(ctx context.Context, request *AccessTfaListUserTfaRequest) (*AccessTfaListUserTfaResponse, error) {

	method := "GET"
	path := "/access/tfa/{userid}"

	var response AccessTfaListUserTfaResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
