// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnControllersIndexRequest struct {
	Pending *bool   `query:"pending,omitempty"` // Display pending config.
	Running *bool   `query:"running,omitempty"` // Display running config.
	Type    *string `query:"type,omitempty"`    // Only list sdn controllers of specific type
}

type ClusterSdnControllersIndexResponse []ClusterSdnControllersIndexResponseItem

type ClusterSdnControllersIndexResponseItem struct {
	Controller string  `json:"controller,omitempty"` //
	Pending    *string `json:"pending,omitempty"`    //
	State      *string `json:"state,omitempty"`      //
	Type       string  `json:"type,omitempty"`       //
}

// SDN controllers index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/controllers
func (c *Client) ClusterSdnControllersIndex(ctx context.Context, request *ClusterSdnControllersIndexRequest) (*ClusterSdnControllersIndexResponse, error) {

	method := "GET"
	path := "/cluster/sdn/controllers"

	var response ClusterSdnControllersIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
