// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDisksLvmthinCreateRequest struct {
	AddStorage *bool  `json:"add_storage,omitempty"` // Configure storage using the thinpool.
	Device     string `json:"device,omitempty"`      // The block device you want to create the thinpool on.
	Name       string `json:"name,omitempty"`        // The storage identifier.
	Node       string `json:"node,omitempty"`        // The cluster node name.
}

type NodesDisksLvmthinCreateResponse string

// Create an LVM thinpool
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/disks/lvmthin
func (c *Client) NodesDisksLvmthinCreate(ctx context.Context, request *NodesDisksLvmthinCreateRequest) (*NodesDisksLvmthinCreateResponse, error) {

	method := "POST"
	path := "/nodes/{node}/disks/lvmthin"

	var response NodesDisksLvmthinCreateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
