// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessUsersTokenUpdateTokenInfoRequest struct {
	Comment *string `json:"comment,omitempty"` //
	Expire  *int64  `json:"expire,omitempty"`  // API token expiration date (seconds since epoch). '0' means no expiration date.
	Privsep *bool   `json:"privsep,omitempty"` // Restrict API token privileges with separate ACLs (default), or give full privileges of corresponding user.
	Tokenid string  `json:"tokenid,omitempty"` // User-specific token identifier.
	Userid  string  `json:"userid,omitempty"`  // User ID
}

// Updated token information.
type AccessUsersTokenUpdateTokenInfoResponse struct {
	Comment *string `json:"comment,omitempty"` //
	Expire  *int64  `json:"expire,omitempty"`  // API token expiration date (seconds since epoch). '0' means no expiration date.
	Privsep *bool   `json:"privsep,omitempty"` // Restrict API token privileges with separate ACLs (default), or give full privileges of corresponding user.
}

// Update API token for a specific user.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/users/{userid}/token/{tokenid}
func (c *Client) AccessUsersTokenUpdateTokenInfo(ctx context.Context, request *AccessUsersTokenUpdateTokenInfoRequest) (*AccessUsersTokenUpdateTokenInfoResponse, error) {

	method := "PUT"
	path := "/access/users/{userid}/token/{tokenid}"

	var response AccessUsersTokenUpdateTokenInfoResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
