// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesSubscriptionDeleteRequest struct {
	Node string `json:"node,omitempty"` // The cluster node name.
}

type NodesSubscriptionDeleteResponse struct{}

// Delete subscription key of this node.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/subscription
func (c *Client) NodesSubscriptionDelete(ctx context.Context, request *NodesSubscriptionDeleteRequest) (*NodesSubscriptionDeleteResponse, error) {

	method := "DELETE"
	path := "/nodes/{node}/subscription"

	var response NodesSubscriptionDeleteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
