// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesStatusNodeCmdRequest struct {
	Command string `json:"command,omitempty"` // Specify the command.
	Node    string `json:"node,omitempty"`    // The cluster node name.
}

type NodesStatusNodeCmdResponse struct{}

// Reboot or shutdown a node.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/status
func (c *Client) NodesStatusNodeCmd(ctx context.Context, request *NodesStatusNodeCmdRequest) (*NodesStatusNodeCmdResponse, error) {

	method := "POST"
	path := "/nodes/{node}/status"

	var response NodesStatusNodeCmdResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
