// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesQemuMonitorMonitorRequest struct {
	Command string `json:"command,omitempty"` // The monitor command.
	Node    string `json:"node,omitempty"`    // The cluster node name.
	Vmid    int64  `json:"vmid,omitempty"`    // The (unique) ID of the VM.
}

type NodesQemuMonitorMonitorResponse string

// Execute Qemu monitor commands.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/qemu/{vmid}/monitor
func (c *Client) NodesQemuMonitorMonitor(ctx context.Context, request *NodesQemuMonitorMonitorRequest) (*NodesQemuMonitorMonitorResponse, error) {

	method := "POST"
	path := "/nodes/{node}/qemu/{vmid}/monitor"

	var response NodesQemuMonitorMonitorResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
