// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessGroupsUpdateGroupRequest struct {
	Comment *string `json:"comment,omitempty"` //
	Groupid string  `json:"groupid,omitempty"` //
}

type AccessGroupsUpdateGroupResponse struct{}

// Update group data.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/groups/{groupid}
func (c *Client) AccessGroupsUpdateGroup(ctx context.Context, request *AccessGroupsUpdateGroupRequest) (*AccessGroupsUpdateGroupResponse, error) {

	method := "PUT"
	path := "/access/groups/{groupid}"

	var response AccessGroupsUpdateGroupResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
