// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterHaGroupsDeleteRequest struct {
	Group string `json:"group,omitempty"` // The HA group identifier.
}

type ClusterHaGroupsDeleteResponse struct{}

// Delete ha group configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha/groups/{group}
func (c *Client) ClusterHaGroupsDelete(ctx context.Context, request *ClusterHaGroupsDeleteRequest) (*ClusterHaGroupsDeleteResponse, error) {

	method := "DELETE"
	path := "/cluster/ha/groups/{group}"

	var response ClusterHaGroupsDeleteResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
