// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterJobsIndexRequest interface{}

// Directory index.
type ClusterJobsIndexResponse []ClusterJobsIndexResponseItem

type ClusterJobsIndexResponseItem struct {
	Subdir string `json:"subdir,omitempty"` // API sub-directory endpoint
}

// Index for jobs related endpoints.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/jobs
func (c *Client) ClusterJobsIndex(ctx context.Context, request *ClusterJobsIndexRequest) (*ClusterJobsIndexResponse, error) {

	method := "GET"
	path := "/cluster/jobs"

	var response ClusterJobsIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
