// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterSdnVnetsSubnetsIndexRequest struct {
	Pending *bool  `query:"pending,omitempty"` // Display pending config.
	Running *bool  `query:"running,omitempty"` // Display running config.
	Vnet    string `query:"vnet,omitempty"`    // The SDN vnet object identifier.
}

type ClusterSdnVnetsSubnetsIndexResponseItem struct {
}

type ClusterSdnVnetsSubnetsIndexResponse []ClusterSdnVnetsSubnetsIndexResponseItem

// SDN subnets index.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/sdn/vnets/{vnet}/subnets
func (c *Client) ClusterSdnVnetsSubnetsIndex(ctx context.Context, request *ClusterSdnVnetsSubnetsIndexRequest) (*ClusterSdnVnetsSubnetsIndexResponse, error) {

	method := "GET"
	path := "/cluster/sdn/vnets/{vnet}/subnets"

	var response ClusterSdnVnetsSubnetsIndexResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
