// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesCapabilitiesQemuMachinesTypesRequest struct {
	Node string `query:"node,omitempty"` // The cluster node name.
}

type NodesCapabilitiesQemuMachinesTypesResponse []NodesCapabilitiesQemuMachinesTypesResponseItem

type NodesCapabilitiesQemuMachinesTypesResponseItem struct {
	Id      string `json:"id,omitempty"`      // Full name of machine type and version.
	Type    string `json:"type,omitempty"`    // The machine type.
	Version string `json:"version,omitempty"` // The machine version.
}

// Get available QEMU/KVM machine types.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/capabilities/qemu/machines
func (c *Client) NodesCapabilitiesQemuMachinesTypes(ctx context.Context, request *NodesCapabilitiesQemuMachinesTypesRequest) (*NodesCapabilitiesQemuMachinesTypesResponse, error) {

	method := "GET"
	path := "/nodes/{node}/capabilities/qemu/machines"

	var response NodesCapabilitiesQemuMachinesTypesResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
