// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterHaGroupsUpdateRequest struct {
	Comment    *string `json:"comment,omitempty"`    // Description.
	Delete     *string `json:"delete,omitempty"`     // A list of settings you want to delete.
	Digest     *string `json:"digest,omitempty"`     // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Group      string  `json:"group,omitempty"`      // The HA group identifier.
	Nodes      *string `json:"nodes,omitempty"`      // List of cluster node names with optional priority.
	Nofailback *bool   `json:"nofailback,omitempty"` // The CRM tries to run services on the node with the highest priority. If a node with higher priority comes online, the CRM migrates the service to that node. Enabling nofailback prevents that behavior.
	Restricted *bool   `json:"restricted,omitempty"` // Resources bound to restricted groups may only run on nodes defined by the group.
}

type ClusterHaGroupsUpdateResponse struct{}

// Update ha group configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/ha/groups/{group}
func (c *Client) ClusterHaGroupsUpdate(ctx context.Context, request *ClusterHaGroupsUpdateRequest) (*ClusterHaGroupsUpdateResponse, error) {

	method := "PUT"
	path := "/cluster/ha/groups/{group}"

	var response ClusterHaGroupsUpdateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
