// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesDisksDirectoryCreateRequest struct {
	AddStorage *bool   `json:"add_storage,omitempty"` // Configure storage using the directory.
	Device     string  `json:"device,omitempty"`      // The block device you want to create the filesystem on.
	Filesystem *string `json:"filesystem,omitempty"`  // The desired filesystem.
	Name       string  `json:"name,omitempty"`        // The storage identifier.
	Node       string  `json:"node,omitempty"`        // The cluster node name.
}

type NodesDisksDirectoryCreateResponse string

// Create a Filesystem on an unused disk. Will be mounted under '/mnt/pve/NAME'.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/disks/directory
func (c *Client) NodesDisksDirectoryCreate(ctx context.Context, request *NodesDisksDirectoryCreateRequest) (*NodesDisksDirectoryCreateResponse, error) {

	method := "POST"
	path := "/nodes/{node}/disks/directory"

	var response NodesDisksDirectoryCreateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
