// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesLxcSnapshotSnapshotRequest struct {
	Description *string `json:"description,omitempty"` // A textual description or comment.
	Node        string  `json:"node,omitempty"`        // The cluster node name.
	Snapname    string  `json:"snapname,omitempty"`    // The name of the snapshot.
	Vmid        int64   `json:"vmid,omitempty"`        // The (unique) ID of the VM.
}

// the task ID.
type NodesLxcSnapshotSnapshotResponse string

// Snapshot a container.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/lxc/{vmid}/snapshot
func (c *Client) NodesLxcSnapshotSnapshot(ctx context.Context, request *NodesLxcSnapshotSnapshotRequest) (*NodesLxcSnapshotSnapshotResponse, error) {

	method := "POST"
	path := "/nodes/{node}/lxc/{vmid}/snapshot"

	var response NodesLxcSnapshotSnapshotResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
