// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type ClusterMetricsServerUpdateRequest struct {
	ApiPathPrefix     *string `json:"api-path-prefix,omitempty"`    // An API path prefix inserted between '<host>:<port>/' and '/api2/'. Can be useful if the InfluxDB service runs behind a reverse proxy.
	Bucket            *string `json:"bucket,omitempty"`             // The InfluxDB bucket/db. Only necessary when using the http v2 api.
	Delete            *string `json:"delete,omitempty"`             // A list of settings you want to delete.
	Digest            *string `json:"digest,omitempty"`             // Prevent changes if current configuration file has different SHA1 digest. This can be used to prevent concurrent modifications.
	Disable           *bool   `json:"disable,omitempty"`            // Flag to disable the plugin.
	Id                string  `json:"id,omitempty"`                 // The ID of the entry.
	Influxdbproto     *string `json:"influxdbproto,omitempty"`      //
	MaxBodySize       *int64  `json:"max-body-size,omitempty"`      // InfluxDB max-body-size in bytes. Requests are batched up to this size.
	Mtu               *int64  `json:"mtu,omitempty"`                // MTU for metrics transmission over UDP
	Organization      *string `json:"organization,omitempty"`       // The InfluxDB organization. Only necessary when using the http v2 api. Has no meaning when using v2 compatibility api.
	Path              *string `json:"path,omitempty"`               // root graphite path (ex: proxmox.mycluster.mykey)
	Port              int64   `json:"port,omitempty"`               // server network port
	Proto             *string `json:"proto,omitempty"`              // Protocol to send graphite data. TCP or UDP (default)
	Server            string  `json:"server,omitempty"`             // server dns name or IP address
	Timeout           *int64  `json:"timeout,omitempty"`            // graphite TCP socket timeout (default=1)
	Token             *string `json:"token,omitempty"`              // The InfluxDB access token. Only necessary when using the http v2 api. If the v2 compatibility api is used, use 'user:password' instead.
	VerifyCertificate *bool   `json:"verify-certificate,omitempty"` // Set to 0 to disable certificate verification for https endpoints.
}

type ClusterMetricsServerUpdateResponse struct{}

// Update metric server configuration.
// https://pve.proxmox.com/pve-docs/api-viewer/#/cluster/metrics/server/{id}
func (c *Client) ClusterMetricsServerUpdate(ctx context.Context, request *ClusterMetricsServerUpdateRequest) (*ClusterMetricsServerUpdateResponse, error) {

	method := "PUT"
	path := "/cluster/metrics/server/{id}"

	var response ClusterMetricsServerUpdateResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
