// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type AccessTfaDeleteTfaRequest struct {
	Id       string  `json:"id,omitempty"`       // A TFA entry id.
	Password *string `json:"password,omitempty"` // The current password.
	Userid   string  `json:"userid,omitempty"`   // User ID
}

type AccessTfaDeleteTfaResponse struct{}

// Delete a TFA entry by ID.
// https://pve.proxmox.com/pve-docs/api-viewer/#/access/tfa/{userid}/{id}
func (c *Client) AccessTfaDeleteTfa(ctx context.Context, request *AccessTfaDeleteTfaRequest) (*AccessTfaDeleteTfaResponse, error) {

	method := "DELETE"
	path := "/access/tfa/{userid}/{id}"

	var response AccessTfaDeleteTfaResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
