// Code generated by gen-api. DO NOT EDIT.

package pve

import (
	"context"
)

type NodesVncwebsocketVncwebsocketRequest struct {
	Node      string `query:"node,omitempty"`      // The cluster node name.
	Port      int64  `query:"port,omitempty"`      // Port number returned by previous vncproxy call.
	Vncticket string `query:"vncticket,omitempty"` // Ticket from previous call to vncproxy.
}

type NodesVncwebsocketVncwebsocketResponse struct {
	Port string `json:"port,omitempty"` //
}

// Opens a websocket for VNC traffic.
// https://pve.proxmox.com/pve-docs/api-viewer/#/nodes/{node}/vncwebsocket
func (c *Client) NodesVncwebsocketVncwebsocket(ctx context.Context, request *NodesVncwebsocketVncwebsocketRequest) (*NodesVncwebsocketVncwebsocketResponse, error) {

	method := "GET"
	path := "/nodes/{node}/vncwebsocket"

	var response NodesVncwebsocketVncwebsocketResponse

	err := c.apiCall(ctx, method, path, request, &response)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
